src/Microsoft.Diagnostics.Runtime/Debugger/Enums.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugClient6.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl2.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl3.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl4.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl5.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugControl6.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugEventContextCallbacks.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugSymbols3.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugSymbols4.cs, src/Microsoft.Diagnostics.Runtime/Debugger/IDebugSymbols5.cs, src/Microsoft.Diagnostics.Runtime/Debugger/Structs.cs, src/Microsoft.Diagnostics.Runtime/Desktop/legacyruntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/threads.cs, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/Utilities/SymbolPath.cs, src/Microsoft.Diagnostics.Runtime/Utilities/pefile.cs
Also collapse the managed definition of WINDBG_EXTENSION_APIS32 and
WINDBG_EXTENSION_APIS64, since they are defined the same.
=> Update debugger interop with stuff from latest dbgeng.h/cvconst.h headers.

src/Microsoft.Diagnostics.Runtime/Desktop/lockinspection.cs
added System.Threading.Monitor.ReliableEnter as waiter method to be detected
Monitor.Enter can be inlined by JIT compiler and we won't see Monitor.Enter in stacktrace. So we have to check for ReliableEnter explicitly.
=> added System.Threading.Monitor.ReliableEnter as waiter method to be detected

src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/heap.cs
Minor improvements to getting ClrMD working more correctly on CoreCLR memory dumps:
* Use the v4.6 GC heap walking code
* Look for basic types in System.Private.CoreLib rather than on mscorlib
=> Core clr fixes

build.cmd
This PR contains a small fix for ``build.cmd`` so it works correctly when the repo is checked out to a path containing a space.
=> Fix build.cmd so it works correctly for paths containing a space

src/Microsoft.Diagnostics.Runtime/Utilities/SymbolLocator.Async.cs
This resolves issue with deadlocks because of the infinite `Wait`on `SynchronizationContext`within applications, for example, in WPF. 
As written in the comment, the issue Microsoft/clrmd#44 can be also fixed by using `ConfigureAwait(false)` on all async or by migrating public API to async - but those changes are much bigger.
=> Fixes issue Microsoft/clrmd#44

src/Microsoft.Diagnostics.Runtime.Tests/HeapTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/PdbTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/heap.cs, src/Microsoft.Diagnostics.Runtime/Desktop/helpers.cs, src/Microsoft.Diagnostics.Runtime/Desktop/legacyruntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/lockinspection.cs, src/Microsoft.Diagnostics.Runtime/Desktop/methods.cs, src/Microsoft.Diagnostics.Runtime/Desktop/modules.cs, src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs, src/Microsoft.Diagnostics.Runtime/Desktop/threadpool.cs, src/Microsoft.Diagnostics.Runtime/Desktop/threads.cs, src/Microsoft.Diagnostics.Runtime/Desktop/types.cs, src/Microsoft.Diagnostics.Runtime/Desktop/v45runtime.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeHeap.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeModule.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeRoots.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeRuntime.cs, src/Microsoft.Diagnostics.Runtime/Utilities/pefile.cs, src/Microsoft.Diagnostics.Runtime/datatarget.cs, src/Samples/WindbgExtension/DumpHeap.cs
-Fixed memory leak in PEBuffer
-Fixed an issue where we don't enumerate a thread when there is a cycle in threads.
-Added a property for the 'Free' type to ClrHeap.
-Added common overrides for PdbInfo to make it play nicer in collections.
=> Various fixes

src/Microsoft.Diagnostics.Runtime.Tests/MethodTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/Targets/SharedLibrary.cs, src/Microsoft.Diagnostics.Runtime/Desktop/v45runtime.cs
#66 Patch for a bug on SOS side when retrieving a method's signature
Sometimes, when the target method has parameters with generic types the first call to GetMethodDescName sets an incorrect value into pNeeded.
In those cases, a second call directly after the first returns the correct value.
+ unit test
=> Patch for a bug on SOS side when retrieving a method's signature

src/Samples/FileAndLineNumbers/Program.cs
Hi!
I have been using part of the code from samples (found it in [msos](https://github.com/goldshtn/msos) project) to display the disassembly code for BenchmarkDotNet and I have realized, that always the last line of source code was printed.
The bug fix was trivial: when you find smaller distance, set the current distance to it. So far the value of distance was always int.Max, so the value of if (dist < distance) was always true, so the loop was going to the end, and returning the last line.
=> find the nearest line, previously was always returning last

src/Microsoft.Diagnostics.Runtime/datatarget.cs
This pr is create at SELA hackathon with Sasha Goldshtein @goldshtn
=> Implement create process snapshot and attach

src/Microsoft.Diagnostics.Runtime/Desktop/fields.cs, src/Microsoft.Diagnostics.Runtime/Desktop/heap.cs, src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs, src/Microsoft.Diagnostics.Runtime/Desktop/v45runtime.cs
Add new BaseDesktopHeapType class named PrimitiveType to host ValueTypes such as Int32/Int16/Bool/Char/Pointer/Etc.
Modify GetBasicType() to return a PrimitiveType object when InitBasicTypes() fails to load the type from mscorlib.  This happens in all MiniDumps.
All the information to be able to extract this data is available to ClrMD, this patch allows us to get this Basic information even when InitBasictypes() can not find the types in a MiniDump.
This allows us to get the same information !sos.do gets in Minidumps.
Example:
!sos.do:
Fields:
MT    Field   Offset                 Type VT     Attr    Value Name
...
640a32b4  4000010       34        System.String  0 instance 02cba4ec _source
00000000  4000011       44        System.IntPtr  1 instance        0 _xptrs
00000000  4000012 …
=> Changes to ClrMD to be able to extract data from Basic types on MiniDumps

src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs
Possible bug: _modules and _moduleFiles in DesktopRuntimeBase is not Flush'ed. So, it's impossible, e.g. get stack traces twice without recreating ClrRuntime
Repro:
```
using (var dt = DataTarget.AttachToProcess(pid, msTimeout, AttachFlag.Passive))
{
var runtime = dt.ClrVersions[0].CreateRuntime();
runtime.Threads.Select(x => x.StackTrace).ToArray();
runtime.Flush();
runtime.Threads.Select(x => x.StackTrace).ToArray();
}
```
Result:
```
Unhandled Exception: Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: You must not reuse any object other than ClrRuntime after calling flush!
ClrModule revision (0) != ClrRuntime revision (1).
at Microsoft.Diagnostics.Runtime.ClrDiagnosticsException.ThrowRevisionError(Int32 revision, Int32 runtimeRevision)
at …
```
=> flush _modules and _moduleFiles in DesktopRuntimeBase

src/Microsoft.Diagnostics.Runtime.Tests/GCHandleTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/Targets/GCHandles.cs, src/Microsoft.Diagnostics.Runtime.Tests/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/Desktop/v45runtime.cs
When dealing with AsyncPinned handles with a state, the v45runtime.EnumerateHandleWorker method returned the interior handle twice
=> Make sure handles are returned only once

Documentation/WalkingTheHeap.md
Remaining questions:
* The text about `Committed` should be likely updated.
* Not sure if `ClrHeap.EnumerateObjectAddresses` should be rather replaced with example using `EnumerateObject`
* Examples of `GCHeapType.Enumerate` should be likely replaced - not quite sure with what.
=> Update WalkingTheHeap tutorial to latest API shape

Src/Microsoft.Diagnostics.Runtime.Tests/FinalizationQueueTests.cs, Src/Microsoft.Diagnostics.Runtime.Tests/Targets/FinalizationQueue.cs, src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/heap.cs, src/Microsoft.Diagnostics.Runtime/Desktop/legacyruntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeDac.cs
Region pointers for "all finalizable objects" and "objects in finalization queue" were mixed up and swapped several times across the code.
This resulted in incorrect processing of data obtained from `V4HeapDetails`.
The fix attempts to bring unified naming for FQ-related stuff and consistent behaviour for all `IHeapDetails` implementations.
The usecase in question was covered by tests, but it would also be nice to get a review due to the lack of docs for `finalization_fill_pointers[i]`.
=> Fix for proper finalization queue detection in .net 4.0+ dumps

src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackFrame.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopStackFrame.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs
This change is to expose the context of stack frames. This change is not applicable to stack frames extracted from an exception where this new field is set to null.
=> Expose context of stack frames

src/Microsoft.Diagnostics.Runtime/src/Common/RuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/ModuleData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopModule.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/IModuleData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V2ModuleData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V4ModuleData.cs
Fixed an issue where we would over-release IMetaDataImport:
- Removed IModuleData.LegacyMetaDataImport entirely.
- Always release metadata pointer when requesting ModuleData for legacy runtimes.
- Specifically re-request the ModuleData struct to get IMetaDataImport for legacy runtimes.
=> Fix issue where we over-release MetaDataImport in legacy runtimes

src/Microsoft.Diagnostics.Runtime.Tests/src/PdbTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/SymbolLocatorTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/Debugger/Structs/ImageCor20HeaderEntryPoint.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopModule.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEFile/ImageDataDirectory.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEFile/PEFile.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEFile/PEHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEFile/ResourceNode.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/COMIMAGE_FLAGS.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/CorHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_FILE.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_OPTIONAL_HEADER_AGNOSTIC.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_OPTIONAL_HEADER_SPECIFIC.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_SCN.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageFileHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageOptionalHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/SectionHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/FileLoader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/SymbolLocator.cs
The old PEFile class used a lot of unsafe code and was overly complex for what it did.  This change implements a new PE reader (PEImage).  PEImage loads most data on demand and does through via straight forward stream reads from the given stream, and only uses unsafe code in a narrow case to convert a byte[] into a a struct.
Fixes https://github.com/Microsoft/clrmd/issues/159.
=> PEImage - Implement a new (cleaner) PE reader

src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs
The compiler doesn't warn about comparing a struct with null unless `strict` is enabled so it's easy to miss it.
=> Fix null ptr check

Directory.Build.props
The compiler enables more warnings if this feature is enabled, eg. comparing IntPtr with null.
=> Enable strict feature

Microsoft.Diagnostics.Runtime.sln, src/Microsoft.Diagnostics.Runtime.UnitTests/AutoFixture/AutoNSubstituteDataAttribute.cs, src/Microsoft.Diagnostics.Runtime.UnitTests/ClrObjectTests.cs, src/Microsoft.Diagnostics.Runtime.UnitTests/Microsoft.Diagnostics.Runtime.UnitTests.csproj
@leculver Produce sample unit tests for ClrObject APIs.
The outcome is not only to have test harness for safety, but also to have code-by-example documentation (how would the API behave in that scenario).
Should I want to use the API, I have to test it on my own now with runtime values ( f.e. attach to simple console app & inspect values in debugger).
Once we have a solid coverage, one may use tests as example to speed up clrMD-based development.
I recall my last PR affected your build server - please be carefull (might need to inject specific project props).
Thanks :)
=> Add logic contracts for ClrObject APIs

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/src/FinalizationQueueTests.cs, src/TestTargets/FinalizationQueue.cs
explicitly check amount of objects in all of the following categories during `runtime.EnumerateFinalizerQueueObjectAddresses()` and `runtime.Heap.EnumerateFinalizableObjectAddresses()`
A: unreferenced finalizable objects in the queue
B: strongly referenced finalizable objects
C: finalizable objects, already not referenced, but not yet in the queue as there was no GC
=> extended test scenario for finalizable objects

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/src/ClrObjectTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/Fixtures/ClrObjectConnection.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs, src/TestTargets/ClrObjects.cs
Key takeaway - DateTime and Guid processing is not yet out-of-the-box.
I referenced AutoFixture to make test neater and reuse one DataTarget fixture-wide.
=> Define contracts for ClrObject functionality

src/Microsoft.Diagnostics.Runtime/src/Common/ClrDiagnosticsException.cs
for the scenarios when exceptions are transferred across process boundaries during multi-process-execution it would be nice to have ClrDiagnosticsException serializable as most of the other default framework exceptions
=> mark ClrDiagnosticsException serializable

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
Symlink the DAC module into a temp file on Linux so it can't load libcoreclrtraceptprovider.so.
=> Fix DAC name on Linux.

src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataMethod.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataTask.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrStackWalk.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetaDataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/CallableComWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComCallableIUnknown.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/UnknownVTable.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/VTableBuilder.cs
- Move COM interop helpers to Utilities namespace.
- Add manual AddRef/Release to COMCallableIUnknown.
- Ensure COMCallableIUnknown will only free data once.
- Allow different return types in VTableBuilder. Now only validate what would cause a crash.
=> COM interop helper cleanup

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader2.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfHeader.cs
Add a way to get the PID on all platforms, and the BuildId for Linux modules.
=> Add DataTarget.ProcessId and ModuleInfo.BuildId

src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/Common/HeapBase.cs
I wanted the ability to access field offsets during enumeration of object references and couldn't find a way to do that without doing an inner scan. It seems the information is available during the outer scan, and this adds API to expose that.
Part of drewnoakes/string-theory#7
=> Enable object reference enumeration with field offset

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs
There are modules like libicui18n.so.60.2 on Fedora version 28 that have more than one NOTE program header. Changed the code to handle it.
=> Fix crash getting build id on Linux.

src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/DefaultSymbolLocator.cs
As far as I can tell the only reason it doesn't work is because of the explicit check of the schema, and this seems to work.
=> Support downloading symbols from https

src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/DefaultSymbolLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/SymPathElement.cs
According to https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-path#caching-symbols-locally a cache* entry is supposed to change the cache path for everything following it. The current implementation instead adds it as a symsrv entry with a null target, which is then later ignored in TryGetFileFromServer.
The documentation is unclear on whether the cache* entry takes precedence over a cache specification inside a srv element, for now I am assuming that it does not.
=> Handle cache* elements in the symbol path.

src/Microsoft.Diagnostics.Runtime.Tests/TestInstructions.txt, src/TestTargets/build_test_assets.cmd
Experimented with tests for a while.
It appeared that `build_test_assets.cmd` sometimes is not that convenient.
With proposed changes the script
- is less dependent on ~dp0, can be placed anywhere, needs just %SourcePath% to be fixed.
- has a bit more verbose error messages
- has predefined placeholders for default `csc` and `cdb` locations right in the script;
changing few lines of code for a single run is usually faster than setting environment variables and making sure they were propagated to the console
=> Update script for building test assets

src/Microsoft.Diagnostics.Runtime.Tests/src/RuntimeTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs
It looks like in recent runtimes few more classes and modules are getting loaded during sample app execution.
Some of the tests started to fail:
- `RuntimeTests.ModuleEnumerationTest` wasn't ready for the presence of the `System` and `System.Core` modules
- `TypeTests.GetObjectMethodTableTest` wasn't ready for the presence of types with generic arguments, `System.Collections.Concurrent.ConcurrentDictionary<System.IntPtr,System.Reflection.Metadata.MetadataReaderProvider>` in particular
=> Fix tests based on the multi-app-domain sample

eng/Versions.props, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj
This will generate assembly, file and package versions based on the build id instead of hard coding it in the project file (to current 1.0.5).  
The package version will look something like this: Microsoft.Diagnostics.Runtime.1.0.35103.nupkg.  The file and assembly versions will have something similar.  
Removed the preview label to generate stable versioning.
=> Update the assembly and package version generation

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs
(proposed for 1.1)
Looks like `IsRuntime` flag is not required anymore.
However there's still some controversial logic around its initialization that would be good to get rid of.
=> Drop obsolete ModuleInfo.IsRuntime

src/Microsoft.Diagnostics.Runtime.Native/src/Common/NativeRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDiagnosticsException.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDiagnosticsExceptionKind.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ExceptionExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Common/HeapBase.cs, src/Microsoft.Diagnostics.Runtime/src/Common/RevisionValidator.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/DumpPointer.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/DumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/MinidumpArray.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/MinidumpExceptionStream.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/MinidumpMemoryChunks.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/MinidumpThreadList.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopModule.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs
(proposed for 1.1)
It would be nice to have an option of getting the original HResult that caused the exception.
This will allow to handle some of the cases more precisely on the client side (e.g. to show different detailed error messages)
PR introduces `ClrDiagnosticsExceptionKind` enum for exception classification (e.g. DacError or DebuggerError).
HResult (where applicable) can be passed via the default `Exception.HResult`.
=> Distinguish exception kind and HResult

src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/Platform.cs
The PR provides a bit more straightforward way for handling clr- and dac-related details.
- dedicated `Platform` enum instead of the `isLinux` flag
- single place which makes all name-related decisions
- logic can be reused by alternative SymbolLocator implementations on client side
Existing apis are kept intact.
=> Extract logic for getting clr details inferred from the module names into a single place

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
While improving parallel stack to attach to process (both on Windows and Linux - https://github.com/chrisnas/DebuggingExtensions/blob/master/src/ParallelStacks.Runtime/ParallelStack.cs#L86), I've faced exceptions on linux.
After debugging and trying to figure out how to use ptrace, I've ended up to this fix: it is not needed to call ptrace on each thread (especially with this type of code/error handling)
=> Avoid crashing on Linux when getting the threads callstack

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
The module file name needs to be the full path for SOS to work and to match the core dump data reader.
=> Fix linux live data reader

src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopModule.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/MemoryRegion.cs
According to https://github.com/dotnet/coreclr/pull/21031 
there's no shared app domain in the latest CoreCLR.
ClrMd fails with nullref in attempt to get SharedDomainAddress in DesktopGCHeap.LoadAllTypes() on such dumps.
=> Handle app domains nullability and absence of shared app domain in the latest CoreCLR

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ReaderStream.cs
Managed binaries did not have a correct filesize and timestamp set when debugging Linux coredumps.
This caused some issues when inspecting Linux coredumps when other code relied on those properties such as ReadVirtual trying to read from module contents.
=> Set FileSize/TimeStamp on coredumps

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Support WSL 1. It doesn't support `/proc/<pid>/mem` but it does support `process_vm_readv()`.
The new code path is only executed if `/proc/self/mem` doesn't exist, i.e., it's WSL 1.
=> Support WSL 1

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
As mentioned in https://github.com/dotnet/corefx/issues/42621, we need to report a better exception when the user specifies an unsupported attach flag on Linux.
=> Throw better exception when failing to attach on Linux

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/TestTargets/GCRoot.cs, src/TestTargets/GCRoot2.cs
This PR makes `GCRoot` get the same results as SOS's for the test target *GCRoot2.cs*.
Test results for *GCRoot2.cs*:
```
> !GCRoot 00000266d568c1d0
HandleTable:
00000266D5321388 (strong handle)
-> 00000266D568C1D0 DirectTarget
00000266D5321390 (strong handle)
-> 00000266D568C1D0 DirectTarget
```
```
> !GCRoot 00000266D568C1E8
HandleTable:
00000266D5321388 (strong handle)
-> 00000266D568C1D0 DirectTarget
-> 00000266D568C1E8 IndirectTarget
Found 1 unique roots (run '!gcroot -all' to see all roots).
```
```
> !GCRoot -all 00000266D568C1E8
HandleTable:
00000266D5321388 (strong handle)
-> 00000266D568C1D0 DirectTarget
-> 00000266D568C1E8 IndirectTarget
00000266D5321390 (strong handle)
-> 00000266D568C1D0 DirectTarget
-> 00000266D568C1E8 IndirectTarget
Found 2 roots.
```
```
GCRoot …
```
=> Fix GCRoot

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs
DataReaders are not properly flushed when the runtime is.
Fixes https://github.com/microsoft/clrmd/issues/303.
=> Flush the DataReader when flushing the runtime

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs
CollectibleTypeTest will non-determinstically fail.  This is because the test would attach to its own process.  Moving this to CreateSnapshotAndAttach makes the test pass all the time.
=> Fix issue with CollectibleTypeTest

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs
ArrayPool.Rent was returning a larger string than we actually needed, and the code pattern in question would cause stray \0's to end up in the generated string.
=> Fix issue where we over-fed string reads

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/RegSetX64.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/DefaultSymbolLocator.Async.cs
This test sample is dangerous: if the parent process crashed due to an assertion failure, the child process won't be killed.
```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
using System.Diagnostics;
using System.Linq;
using Xunit;
namespace Microsoft.Diagnostics.Runtime.Tests
{
public class DataTargetTests
{
[Fact]
public void SuspendAndAttachToProcess()
{
using Process process = Process.Start(new ProcessStartInfo
{
FileName = "...",
Arguments = "...",
RedirectStandardOutput = true,
});
_ = process.StandardOutput.ReadLine();
using (DataTarget dataTarget = DataTarget.SuspendAndAttachToProcess(process.Id))
{
ClrRuntime runtime = …
```
=> Implement SuspendAndAttachToProcess on Linux

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Closes #264 
`process_vm_readv` is faster and doesn't raise exceptions or signals.
Benchmark results
|  Method |      Mean |     Error |    StdDev |
|-------- |----------:|----------:|----------:|
| ProcMem | 13.869 ms | 0.3094 ms | 0.9122 ms |
|   Readv |  6.353 ms | 0.1366 ms | 0.4029 ms |
Benchmark sample
```cs
using System;
using System.Buffers;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.Diagnostics.Runtime;
public class Program
{
static void Main() => _ = BenchmarkRunner.Run<Program>();
static readonly DataTarget dataTarget = DataTarget.PassiveAttachToProcess(1);
static readonly IEnumerable<ModuleInfo> modules = dataTarget.EnumerateModules();
[Benchmark]
public void ReadMemory()
{
foreach (ModuleInfo module in …
```
=> Don't read from /proc/<pid>/mem

src/Microsoft.Diagnostics.Runtime/src/Implementation/HeapBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/RuntimeBuilder.cs
-Segment enumeration was mistakenly started from the EphemeralHeapSegment instead of the first Gen2 segment.
- We did not properly account for the meaaning of fieldInfo.NumFields.  This includes the base type's field count, so we did not need to add that.
- ContextStatics and ThreadStatics are included in "NumStaticFields".  Need to be sure count those as we are walking fields.
=> Fields and segments

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Common/VersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfProgramHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/MemoryVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfProgramHeaderAttributes.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/FileLoader.cs
Fixes #148 
Fixes #306 
`GetFileVersion` works for any *.so* file.
```
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Native.so
v0.0.0.00
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libclrjit.so
v0.0.0.00
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
v4.700.19.46205
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libhostpolicy.so
v3.0.19.46706
/usr/share/dotnet/host/fxr/3.0.0/libhostfxr.so
v3.0.19.46706
```
```
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Native.so
v4.700.19.46214
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libclrjit.so
v4.700.19.46205
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
v4.700.19.46205
/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/libhostpolicy.so
v3.0.19.46706 …
```
=> Implement GetFileVersion/GetVersionInfo on Linux

src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueClass.cs, src/Microsoft.Diagnostics.Runtime/src/Common/IAddressableTypedEntity.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ValueReader.cs
Added a maximum length to read from strings to prevent OOM/Overflow if there's corrupt memory.
Fixes https://github.com/microsoft/clrmd/issues/244.
=> Add max length of string reads

src/Microsoft.Diagnostics.Runtime.Tests/src/AppDomainTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/DataTargetTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/ExceptionTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/FieldTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/FinalizationQueueTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/GCHandleTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/MethodTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/MinidumpTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/PdbTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/RuntimeTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/CallableComWrapper.cs
- ClrRuntime is now an IDisposable.
- Properly disposing of ClrRuntime ensures that all interfaces and the DacLibrary are completely released.  Not disposing of ClrRuntime is fine, but cleanup and release of libraries and interfaces will happen on the finalizer thread.
- ClrRuntime.FlushCachedData is now properly implemented and mostly tested.
=> Ensure ClrRuntime properly cleans up

.gitignore, Microsoft.Diagnostics.Runtime.sln, ParallelStressTest/App.config, ParallelStressTest/ParallelStressTest.csproj, ParallelStressTest/Program.cs, ParallelStressTest/Properties/AssemblyInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/HeapWalkStep.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Initial implementation of support for parallel processing.  Not all data targets have been marked as threadsafe yet.  Only DbgEngDataReader and Windows's LiveDataReader are currently thread safe.
Note that we do _not_ expect to see any perf improvements by running ClrMD operations in parallel.  This is because the underlying diagnostics API mscordac*.dll takes a giant lock around any call we make, and many IDataTarget implementations will similarly need to take a lock around from the target.
Using ClrMD from multiple threads is primarily for convenience.  That is, not having to keep ClrMD locked to a single thread, you can now use it with in an async/await context, for example.  This also allows parallel processing for user code if you are in a scenario where you only need to read from …
=> Allow ClrMD to be used from multiple threads

src/Microsoft.Diagnostics.Runtime.Tests/src/CacheOptionsTest.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/CacheOptions.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrMethod.cs, src/Microsoft.Diagnostics.Runtime/src/Common/StringCaching.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdMethod.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IMethodHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeHelpers.cs
We need to give users a mechanism to tell ClrMD what to cache and what not to.  This change gives the user the ability to choose whether ClrMethods, ClrTypes, and Clr*Fields (and their respective names) get cached or are regenerated on every call.  The default behavior remains unchanged: All types are cached by default and all names are cached (but not interned) by default.
I may need to rewrite how we get fields, in only creating instance/static fields individually instead of both at the same time when we aren't going to cache the result.  In general though, I'm not super concerned about that right now, since not caching fields is going to be super slow anyway.
=> Implement caching options

src/Microsoft.Diagnostics.Runtime/src/Builders/FieldBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/MethodBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/ObjectPool.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/TypeBuilder.cs
Thread static fields keep ConcurrentBag alive too long.  This lead to fast growing memory leaks.
We don't need something as heavyweight as ConcurrentBag.  A queue with a lock is just fine.
=> Stop using ConcurrentBag

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs
Fixes https://github.com/microsoft/clrmd/issues/394.
Ensure we correctly parse generic type names without ` airty.
=> Update FixGenerics to work when there's no arity

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxDefaultSymbolLocator.cs
- When enumerating stack traces, use valid context offsets depending on the target architecture.
- When resolving symbols in LinuxDefaultSymbolLocator, enforce File.Exists() check for module paths provided by CoreDumpReader to verify their existence in the current filesystem, to avoid any IOExceptions.
A side note:
Instead of using hard-coded offsets, the values can be programatically obtained from existing structures ([ArmContext](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DataReaders/Registers/ArmContext.cs), [Arm64Context](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DataReaders/Registers/Arm64Context.cs), etc.), or even we can marshal the `byte[] context` array into those structures.
=> Fix for Linux ARM

src/Microsoft.Diagnostics.Runtime.Utilities/Microsoft.Diagnostics.Runtime.Utilities.csproj, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSymbols.cs
Using netstandard isn't buying us anything since we already ship two copies of the library anyway.  Just use netcoreapp instead.
=> Use .Net Core instead of Netstandard for the library

src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs
Alternative fix for #422.
Yeah, CorHeader (#192) is already there but never used.
=> Fix metadata reading

src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
2.0 had a regression wherein DefaultPdb would return null though the
binary had valid debug info embedded. The correct offset is now being
used to check for the CV7 signature, thereby fixing the regression.
=> Fix regression in ReadPdbs

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
This does not clean up implementations of EnumerateModules to do their work lazily.
=> Use IEnumerable instead of IList in IDataReader.EnumerateModules

src/Microsoft.Diagnostics.Runtime.Tests/src/PEImagePdbTests.cs
These tests validate that the property works correctly for PDBs for managed and unmanaged binaries.
=> Add tests for PEImage.DefaultPdb

src/Microsoft.Diagnostics.Runtime.Tests/src/MemoryReaderTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/MemorySearcher.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
- Searching through memory to look for a sequence of bytes is a useful thing to have.
- Simplify GetVersionInfo on Linux by using SearchMemory, and by manually parsing the ascii version string.
- Simplify reading of Ascii characters in ReadNullTerminatedAscii.  Since the text we are looking for will have the matching code points between ascii and unicode we can just Append them directly to StringBuilder and not go through Encoding.
=> Implement IDataReader.SearchMemory

src/Microsoft.Diagnostics.Runtime.Tests/src/MemoryReaderTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/MemorySearcher.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
- Add todo marker where we need to improve memory searching in the future.
- Remove Console.WriteLines.
- Change SearchMemory to use a length.
=> Memory searcher cleanups

src/TestTargets/FinalizationQueue/FinalizationQueue.cs, src/TestTargets/TestTargets.proj
Fixes https://github.com/microsoft/clrmd/issues/436.
It's unclear to me if I've really fixed the problem or made it harder to observe.  I wasn't able to figure out how the previous version of the tests would get into their state even after debugging the offending crash dumps.
=> Make FinalizerQueue tests fail less often

src/Microsoft.Diagnostics.Runtime.Tests/src/PEImagePdbTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/PEImageResourceTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
Fixes https://github.com/microsoft/clrmd/issues/465.
- Removed the shared PEImage from ModuleInfo.
- Ensure thread safety when reading PEImage from multiple threads by taking a lock when calling into PEImage.
- Made PEImage artificially IDisposable for future work.
=> Make PEImage usage thread safe

src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandle.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandleKind.cs
To reproduce: follow the steps referenced by dotnet/coreclr#27860 and call `ClrmdRuntime.EnumerateHandles()` when the process crashes.
https://github.com/dotnet/runtime/blob/afc21e51af60a4d2cb11a1081fb38b1e3a8df0a2/src/coreclr/src/gc/gcinterface.h#L424-L436
https://github.com/dotnet/runtime/blob/afc21e51af60a4d2cb11a1081fb38b1e3a8df0a2/src/coreclr/src/debug/daccess/request.cpp#L3255-L3257
=> Add weak WinRT handle kind

azure-pipelines.yml
Continued from https://github.com/microsoft/clrmd/commit/526c03061dae6a2a5bc4c18a475281e1ec1fc09e
Editors are reporting that these strings are invalid, but Azure Pipelines' YAML parser works differently.
=> Remove double quotes in azure-pipelines.yml

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs
Fixes #506 
There is no "basic type" for `System.Array`.
`System.String` is missing here - not sure if it's intentional.
=> Remove System.Array from GetOrCreateBasicType

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs
I am proposing two fixes in this PR.
The first fix eliminates an unhandled exception on Linux when:
- I am processing a .NET Core 3.0 Linux core dump,
- I don't have .NET Core 3.0 installed on the Linux box, and
- I placed `libmscordaccore.so` at the current directory running the tool using CLRMD.
This was done as an attempt to make CLRMD loads the DAC I wanted, that doesn't worked because:
`DataTarget.GetOrCreateClrVersions()` was returning the DAC file name as DAC location.
Eventually, the file name is used in `ClrInfo.CreateRuntime()` as the `LocalMatchingDac`:
https://github.com/microsoft/clrmd/blob/0dad83b95254477aa91682e51dcec7d2cb192904/src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs#L83-L99
The file name will pass the `File.Exists()` tests if `libmscordaccore.so` is …
=> Fix dac loading

src/Microsoft.Diagnostics.Runtime/src/Implementation/ValueReader.cs
In case the string is empty, the `ReadString()` method is reading exactly 0 bytes from the underlying `IDataReader`. For Windows, this will return true as `0 == 0`
https://github.com/microsoft/clrmd/blob/b43792a2dc63f51a400167b103d3dc8f8c663cc9/src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs#L271-L275
But on Linux, this will return false as `0 > 0` is not true.
https://github.com/microsoft/clrmd/blob/b43792a2dc63f51a400167b103d3dc8f8c663cc9/src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs#L154-L160
While this inconsistency is worrisome, this can be easily avoided by not using the reader when we already knew it is an empty string, which is probably the right thing to do anyway.
=> Avoid reading empty string

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
`IMemoryReader.Read(ulong, Span<byte>, out int)` is documented to return "true if any bytes were read at all".
The call site needs to determine whether incomplete reads make sense.
/cc @cshung
=> Make Read implementations consistent

src/Microsoft.Diagnostics.Runtime.Tests/src/ByReferenceTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrSegment.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackInteriorRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrThread.cs, src/Microsoft.Diagnostics.Runtime/src/Common/IClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdThread.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IThreadHelpers.cs, src/TestTargets/ByReference/ByReference.cs, src/TestTargets/ByReference/ByReference.csproj
Fixes https://github.com/microsoft/clrmd/issues/539 and https://github.com/microsoft/clrmd/issues/532.
This change ensures we properly enumerate interior stack pointers.  I also added back ClrSegment.NextObject as GetNextObjectAddress.
=> Properly handle interior stack pointers

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopException.cs
If we fail to get the type of an inner exception, do not produce a ClrException object for it.  This prevents us from hitting random null ref exceptions later in execution.
=> Don't create inner exceptions if the type is null

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj
Building test assets with "AfterTargets=Build" is currently breaking the arcade build system signing step.  This only happens within Arcade and no one on that team has been able to figure out why.  Disabling this part of the build for now so we can get 2.0-beta builds out the door.
=> Temporarily disable test asset building

src/Microsoft.Diagnostics.Runtime/src/Common/ContextHelper.cs
For release/1.1
Similar to #421 (master), but ProcessArchitecture == DataTarget.Architecture is assumed (we don't support cross-debugging scenario).
=> Support ARM/ARM64 contexts

src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs
Calling ISOSDac::GetMethodTableData with a TypeHandle will always fail, and it will do some expensive C++ exception handling along the way.  Instead, don't bother calling GetMethodTableData if we know the value is a TypeHandle.
This is intentionally a minimal change.
=> Don't request MethodTableData for TypeHandles

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj
Testing changes to see if the restore from building unit tests is what's interfering with the pack phase of arcade's internal build.
=> Don't restore when building test targets

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj
This reverts commit dc3f52229ee145b4de5d7fe610c076feb5a6d87a.
This was not the cause of the arcade build break, so I'm reverting this change.
=> Revert "Don't restore when building test targets (#590)"

Directory.Build.props, Directory.Build.targets, azure-pipelines.yml
Temporarily disable code coverage to see if this is what is causing Arcade build breaks on the internal server.
=> Temporarily disable code coverage

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataMethod.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataModule.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataTask.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrStackWalk.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac6.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugAdvanced.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugClient.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugControl.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugDataSpaces.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSymbols.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSystemObjects.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/CallableComWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComCallableIUnknown.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/HResult.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/VTableBuilder.cs
- Intentionally start accepting more SUCCEEDED(hr) instead of hr == S_OK.
- Created an HResult struct to wrap COM's HRESULT.
- HResult has an implicit int cast operator for convenience.
- HResult has an implicit bool cast operator which is the equivalent of "SUCCEEDED(hr)".
- Change most wrappers to use and return HResult instead of bool.
- Functionality should be mostly unchanged, but allows for better control/error flow.
=> Use HRESULT instead of bool

src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSystemObjects.cs
DbgEng does not actually support loading multiple dumps at the same time.  It is designed in a way that *should* support it, but the actual implementation is not well tested and contains many bugs.  This means that loading two dumpfiles at the same time will not be successful.
=> Don't set System Id in DbgEng

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrFieldReference.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs
Add a way to enumerate references of an object with a source of where that reference came from.
=> Add ClrObject.EnumerateReferencesWithFields

src/Microsoft.Diagnostics.Runtime.Tests/src/Fixtures/ArrayConnection.cs, src/Microsoft.Diagnostics.Runtime.Utilities/Debugger/Structs/DebugOffsetRegion.cs, src/Microsoft.Diagnostics.Runtime.Utilities/Debugger/Structs/DebugSymbolSourceEntry.cs, src/Microsoft.Diagnostics.Runtime.Utilities/Debugger/Structs/ImageCor20HeaderEntryPoint.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrException.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrReference.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueType.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ComInterfaceData.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCDesc.cs, src/Microsoft.Diagnostics.Runtime/src/Common/HotColdRegions.cs, src/Microsoft.Diagnostics.Runtime/src/Common/MemoryRegionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Common/VersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataAddress.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Registers/Float80.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/AllocationContext.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/FinalizerQueueSegment.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfAuxv32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfAuxv64.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfHeader32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfHeader64.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfHeaderCommon.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/CorHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_COR20_HEADER_ENTRYPOINT.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageFileHeader.cs
- Make structs `readonly` where possible in the `Microsoft.Diagnostics.Runtime` assembly
- Remove some redundant `readonly` member modifiers
- Mark some members of `ClrArray` as `readonly`
=> Usage of readonly structs and members on structs

src/Microsoft.Diagnostics.Runtime.Tests/src/PEImageResourceTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs
The dotnet-dump's `lm` command and any command run for the first time has a huge perf problem. The modules are enumerated to find the runtime module. Getting the Version for each PE image in the Linux core dump was taking way too long and failing.
The problem is the "layout" of managed PE modules. Some PE's are "file" layout and some are "loaded" (sections are aligned) layout in memory. The "isVirtual" flag in the PEImage constructor needs to be set based on the layout, but there is no way to determine that at the core dump data reader level. If the layout/isVirtual flag is set incorrectly, PEImage doesn't enumerate through the resources correctly, takes a long time because it is reading really long garbage strings, etc.
IDataReader.EnumerateModules() is meant to return just native …
=> Improve ELF reader EnumerateModules() perf

src/Microsoft.Diagnostics.Runtime/src/Builders/MethodBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/MethodDescData.cs
- Use unsigned integers for everything related to MethodTable slots.
- Change DacTraverseModuleMap to accept an enum instead of using an int which has to be casted.
=> Casting fixes

src/Microsoft.Diagnostics.Runtime.Tests/src/BinaryLocatorTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/PEImagePdbTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
ModuleInfo changes:
- Change _isVirtual to be private
- Mark the class sealed
- Keep a reference to DataTarget instead of IDataReader
- Rename FileSize/Timestamp fields
PEImage changes:
- PEImage now contains a flag for whether to leave the stream open or not
- Clean up PEImage.Dispose related methods
- Make PEImage.Stream private
- Change PEImage.Reader to be nullable
Other:
- Update LinuxLiveDataReader to not need to write to IsVirtual
- Update DacInfo to not derive from ModuleInfo
=> Rework ModuleInfo

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs
We don't need an extra entry in the step.  Defensively check for >= instead of ==.
=> Fix index out of bounds exception

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeHelpers.cs
FixGenerics is called by ITypeHelpers.GetTypeName.  ClrmdType shouldn't also call it.
=> Don't call FixGenerics twice

src/Microsoft.Diagnostics.Runtime/src/Common/ClrElementTypeExtensions.cs
`ELEMENT_TYPE_PTR` and `ELEMENT_TYPE_FNPTR` are not primitive types.
Primitive types are also value types.
=> Fix ClrElementType extensions

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Contributes to #625 
Some questions:
- `IDataReader.GetVersionInfo` is a `void` method with an `out` parameter?
=> Lazily initialize ModuleInfo.BuildId

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
It can take a long time to produce the build id and version for various modules.  This change ensures that we calculate those values on demand.
=> Ensure ModuleInfo's BuildId and VersionInfo are lazily evaluated

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/src/DataReaders/LinuxSnapshot/LinuxSnapshotTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
(I haven't yet tested this checkin.)
Adding support for linux seemed oddly easy.  @mikem8361 do you think this would work taking a snapshot of your own process?  Have you ever tested that before?
I was reading through `DiagnosticsClient` and even though we'd pause before getting the IPC response everything _seems_ like it would work?  I'll do more testing before merging this change.
Also @NextTurn for code review, though it's a simple change.  I hate that I can't ask for reviews outside of the dotnet foundation...
I am using ArgumentException for errors attaching to a process.  That originally came from the fact that Process.GetProcessById will throw ArgumentException when the process isn't valid.  It still seems a bit odd to throw such a generic exception instead of something more …
=> Add Linux support for CreateSnapshotAndAttach

src/Microsoft.Diagnostics.Runtime.Tests/src/ExceptionTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/MinidumpTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/NullBinaryLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/StringReader.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrException.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IExceptionHelpers.cs
- Added a fallback for exception offsets in case we cannot locate the module the original data came from.
- Hardcoded string offsets because the only versions of the runtime we support contains the same length/data offsets.  We would need to revisit this scenario if that changes in the future.
Fixes https://github.com/microsoft/clrmd/issues/406.
=> Add a fallback for exception/string offsets

src/Microsoft.Diagnostics.Runtime.Tests/src/NullBinaryLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Common/IBinaryLocator.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxDefaultSymbolLocator.cs
- Recent changes lost the code that checked _NT_SYMBOL_PATH.
- Add a method to IBinaryLocator for getting files by buildId.  This is not yet implemented.
=> Fix symbol server path regression

src/Microsoft.Diagnostics.Runtime.Tests/src/AppDomainTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/Helpers.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/MethodTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/RuntimeTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/StaticFieldTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/ModuleBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs
Remove ClrMD.FileName.  This property was only a mirror of .Name when IsPEImage was true.  There's no reason to have both of these.
Closes https://github.com/microsoft/clrmd/issues/529.
=> Clean up ClrModule.Name/FileName

src/Microsoft.Diagnostics.Runtime.Tests/src/Helpers.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/StaticFieldTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrField.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrInstanceField.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStaticField.cs
The original design of ClrStaticField was to use the AppDomain associated with its parent type.  This made it very difficult to walk the value of that static field in all AppDomains as it's difficult to have ClrMD find and construct all of the concrete ClrTypes for each domain.  Instead we'll just require the user to pass the ClrAppDomain of the value to read.  They can always use "staticField.Parent.Module.AppDomain" to get the previous behavior.
=> Change ClrStatcField to require AppDomains

src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs
=> Replace nameof(T)

src/Microsoft.Diagnostics.Runtime/src/Common/ClrReference.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs
- We calculated the wrong offset for LoH object ranges.
- A missing 0x value meant values were in octal instead of hex.
=> Fix issues with enumerating the heap and references

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/Minidump.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/MinidumpMemoryReader.cs
Contributes to #660 
Interestingly enough, the simplest use of MMF increases performance significantly for my test case.
The MMF doesn't allow any file sharing by default so there can only be one stream at the same time. (Why do we need two streams?) I made `MinidumpReader` the `IDataReader` responsible for the disposal.
=> Use memory mapped files for minidump

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrElementType.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrEnum.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdConstructedType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdGenericType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdPrimitiveType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/SigParser/SigParser.cs
This change essentially rewrites ClrmdField.GetTypeForFieldSig and instead implements that function as a real type signature parser.
- Move ClrmdField.GetTypeForFieldSig -> ITypeFactor.GetOrCreateTypeFromSignature.
- Implement most of ECMA 355 II.23.2.12 (type signature parsing) instead of the hacky version I wrote originally.
- Promote EnumerateGenericParameters to be a property instead of enum.
- Add ClrmdGenericType which is a "fake" constructed type for when we cannot properly look up a type.
During this change I promoted EnumerateGenericParameters from an enumeration to a property with a backing field.  This was a bad choice that I will revert before checkin, the original code was better.
Most types don't need that field, and we only need to go through GetOrCreateTypeFromSignature …
=> Better type signature parsing

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/SyncBlock.cs, src/Microsoft.Diagnostics.Runtime/src/Common/SyncBlockFlags.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ComSyncBlock.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/FullSyncBlock.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IHeapHelpers.cs
- Greatly improves AsComCallableWraper and AsRuntimeCallableWrapper performance (after the first call, which warms up the cache).
- Added ClrObject.SyncBlock, ClrObject.IsComCallableWrapper, and ClrObject.IsRuntimeCallableWrapper.
=> Add support for SyncBlocks

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs
Objects aren't COM wrappers, they either have them or don't.  This change brings ClrMD into line with that changing As->Get and Is->Has.
=> Rename COM concepts

src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs
Fixes #671 
hr = S_FALSE
needed = 0
EnumerateInterfaces() yielded no results.
Similar fixes may be required for other methods where `needed - 1` is used.
=> Return null string for S_FALSE

src/Microsoft.Diagnostics.Runtime/src/Common/ClrReference.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
Added a way to walk the inner fields of an `ClrReference`.  For example, if you have class:
struct Bar
{
object o;
}
class Foo
{
Bar b;
}
Then enumerating the references of Foo can find "b.o" by using:
ClrReference? reference = obj.EnumerateReferencesWithFields();
while (reference is ClrReference r)
{
// use r
reference = r.InnerField;
}
=> Inner fields

src/Microsoft.Diagnostics.Runtime/src/Common/GCDesc.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/SpanExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
The previous code would individually read one pointer at a time as we walked objects for references.  Now read in the entire object into one buffer before walking the object.
=> Don't read gcdesc pointers one at a time

src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs
It's common for the QueryInterface for IMetaDataImport to fail if the dump file does not contain all of the metadata.  This is especially common in non-heap dumps and Watson dumps.  This change adds an extra QueryInterface to make sure this call will succeed before trying to create a MetadataImport instance.  This should greatly reduce the number of exceptions being thrown under normal operation.
Contributes to https://github.com/microsoft/clrmd/issues/416.
=> Don't throw an exception if we fail to QueryInterface IMetaDataImport

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/OSXFunctions.cs
This is so dotnet-dump can support the ELF core dumps generated by the new createdump on MacOS.
=> Support MacOS PlatformFunctions.

src/Microsoft.Diagnostics.Runtime/src/Common/ClrField.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs
ClrField.Type and ClrValueType.Type can actually be null.  Even if the 99% case is that they are non-null we need to mark them appropriately for error handling.
=> Mark ClrField.Type and ClrValueType.Type as nullable

src/Microsoft.Diagnostics.Runtime/src/Common/ObjectSet.cs
Fixes an ancient issue.
CA1819 recommends to return a collection but it's gonna hurt the performance.
=> Change ObjectSet's fields to properties

src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs
This is failing in some cases I don't understand, so I'm backing out the public surface area
of this feature until it's fixed.
https://github.com/microsoft/clrmd/issues/712
=> Remove ClrModule.SimpleName

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs
- Make GCRootProgressUpdatedEventHandler take a long instead of int, just in case.
- Change "unique" -> "returnOnlyFullyUniquePaths".
=> GCRoot surface area changes

src/Microsoft.Diagnostics.Runtime/src/Common/ClrReference.cs
Primitive fields are recursively defined, which means if we incorrectly blame a ClrReference.InnerField on one, we can create infinite loops in customer code.
I'm still working on why we blame the wrong field, but this stops the loop in case we do.
=> Fix an infinite chain when ClrReference.InnerField fails to blame correctly

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
SOSHandleEnum seems to have a memory leak on Desktop CLR.  This is causing benchmarks to fail with OutOfMemoryException.
We can sometimes avoid the leak if we pass an array that's so large that it's filled on the first pass and we don't need to loop around fetching more.
Fixes https://github.com/microsoft/clrmd/issues/727.
=> Fix SOSHandleEnum memory leak

src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntryFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntryFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CacheEntryBase.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CachePage.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CachedMemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/HeapSegmentDataCache.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/SegmentCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/SegmentCacheEntryFactory.cs
This change refactors and (I hope) drastically simplifies the cache entries and locking story around them as well as fixing a few bugs I found along the way.
The specific high-level changes:
Make a common base class (CacheEntryBase<T>) that represents most of the complexity that is shared between the ArrayPool and AWE cache entries. Most significantly, lock management.
Greatly simplify the locking scheme. Previously if you made a read that required accessing N pages of data I would require locking all N pages of data and ensuring they were all paged in before continuing with the read. I now stream the reads so we lock/page-in/read one page of the request at a time. This allows better granularity of concurrent reads as well as drastically simplifying lock management. It also allows us to …
=> Refactor cache entries

src/Microsoft.Diagnostics.Runtime/src/Windows/CacheEntryBase.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/HeapSegmentDataCache.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/SegmentCacheEntry.cs
Stop using longs to represent time stamps
Stop using QPC/Interlocked.Exchange to update time stamps
The timestamps are only used for comparing the access temporality of two cache entries to select the least recently accessed of the two and select the least recently amongst all entries for removal if we need to keep the cache under its cap size. To that end it doesn't matter if unprotected RMWs (Read/Modify/Write) lead to 'losing' access 'ticks' as the odds of a lost tick placing a recently accessed heap segment into the trim bucket incorrectly is essentially 0.
=> Perf tuning on heaps segment cache 

src/Benchmarks/BenchmarkSwitches.cs, src/Benchmarks/HeapBenchmarks.cs, src/Benchmarks/ParallelHeapBenchmarks.cs, src/Benchmarks/Program.cs
Benchmarks take a very long time.  I'm going to scope down what we test just to some key values that are the defaults in clrmd.
=> Reduce the overall number of benchmarks

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs
The ??= operator is the wrong choice when the value can be changed out from under it.  After assignment another thread can flush cached data and we will return null.
=> Fix threading issue with ClrRuntime.BaseClassLibrary

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj
In the future (such as ClrMD 2.1 or 2.2) we will likely move the version back forward to 4.7.1.  This change is to enable some usage of ClrMD where 4.6.1 is used.
=> Roll version back to 4.6.1

src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs
For the code:
<details>
<summary>Details</summary>
```C#
using Microsoft.Diagnostics.Runtime;
using System;
using System.IO;
using System.Linq;
namespace ConsoleApp1
{
class Program
{
static void Main(string[] args)
{
if (args.Length != 1) throw new ArgumentException(nameof(args));
if (!File.Exists(args[0])) throw new FileNotFoundException(args[0]);
var dataTarget = DataTarget.LoadCrashDump(args[0]);
var runtime = dataTarget.ClrVersions?.Select(x => x.CreateRuntime()).FirstOrDefault();
if (runtime == null) throw new NullReferenceException(nameof(runtime));
var @throw = runtime.EnumerateMemoryRegions().ToList();
}
// ConsoleApp1.exe "C:\tmp\ConsoleApp.DMP"
}
}
```
</details>
Application throws:
<details>
<summary>Details</summary>
```
Unhandled Exception: System.ArgumentException: Field …
```
=> Fix LegacyRuntime.EnumerateJitHeaps

src/Microsoft.Diagnostics.Runtime.Tests/src/DataTargetTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
This property should never have been exposed.  The real 'parent' of a ModuleInfo is an IDataReader, which is what this property should have been.  For now I'm marking the old property obsolete until a major release.
Fixes https://github.com/microsoft/clrmd/issues/754.
=> Mark ModuleInfo.DataReader obsolete

src/Microsoft.Diagnostics.Runtime.Tests/src/ThreadReaderTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IThreadReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSystemObjects.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/Minidump.cs
- Added an optional interface for IDataReaders which preserves some ClrMD 1.1 functionality.
- WindowsLiveDataTarget doesn't currently implement this.
=> Add IThreadReader

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs
SOS requires us to be able to know the size of an image in memory.  This unblocks some functionality by letting us use the SizeOfImage on coredumps for this purpose.
=> Add a fake "SizeOfImage" on Linux

src/Microsoft.Diagnostics.Runtime.Tests/src/ThreadReaderTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/Minidump.cs
This change moves 2.0 to match ClrMD 1.1 behavior, where we ensure that threads are enumerated in the order they exist in minidumps and coredumps.
Note that this does _not_ guarantee any particular ordering, such as assume the first thread is the "main" thread.  Programs that create crash and coredumps are able to set any particular ordering in the dumps.  It's valid to create crash dumps and coredumps where the first thread in the stream is not the main thread, so you should not take any dependency on ordering.
=> Ensure threads are enumerated in the same order as dumps

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs
The GC sets the low bit on method tables when marking objects.  We need to ignore this bit, but the code that masked the bit off was lost in rewrite.
=> Fix heap walking issue when the marking bit is set

src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
When there's not enough of the PE image to fully initialize a PEReader object it can throw an EndOfStreamException.
=> Silence PEReader exception

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs
Same implementation as in ClrMD 1.1
=> FIX: missing case in GetMethodByInstructionPointer()

Microsoft.Diagnostics.Runtime.sln, src/Microsoft.Diagnostics.Runtime.Tests/src/BasicArrayTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs
- Reverts #787 - it did nothing.
- Deprecates `GetStructValue(int, bool)` - in ClrMD you simply can't get a non-interior struct value.
- Adds multi-dimensional `GetStructValue`.
- Fixes multi-dimensional `GetObjectValue`.
- Resolves code duplication.
- Reduces generic instantiation.
=> Tweak ClrArray

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
This fixes the following issues:
1) SOS for Linux dumps generated on MacOS. The ModuleInfo ImageSize wasn't being set in this case. The ElfLoadedImage.Size is set to an appropriate value even for MachO in-memory images but when ElfLoadedImage.Open fails and PEImage.ReadIndexProperties is called the file size variable is set to 0. Rearranged the code to preserve the Size.
2) Made PEImage.ReadPdbs() more bullet proof and changed it not to return "default" which causes PEImage.DefaultPdb to hit an null ref. The try/catch added isn't as neccesary anymore because of fix #3.
3) Fixed module PDBInfo and Version for PE images in ELF coredumps. When building the module infos changed the CoreDumpReader's to always pass isVirtual to true. The _containsExecutable flag is the right value. It meant …
=> Fix ELF reader for MacOS generated dumps and other changes

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Registers/Arm64Context.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Registers/X86Context.cs
This is important because if the context is returned back to DBI/DAC like it is in dotnet-dump, the context isn't internally copied correctly causing the SOS `clrstack -i` commands to fail.  
DAC/DBI code does this:
if ((dstFlags & srcFlags & DT_CONTEXT_CONTROL) == DT_CONTEXT_CONTROL)
=> Fix the architecture bit in the arm64/x86 context flags

src/Microsoft.Diagnostics.Runtime/src/Linux/MemoryVirtualAddressSpace.cs
When there are problems with loading an ELF header, a `NullReferenceException` is thrown with "The method or operation is not implemented" message as shown in the following example, making really hard to understand what's happened.
```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
at Microsoft.Diagnostics.Runtime.Linux.MemoryVirtualAddressSpace.get_Name()
at Microsoft.Diagnostics.Runtime.Linux.ElfFile..ctor(Reader reader, Int64 position, Boolean isVirtual)
at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.GetElfFile(UInt64 baseAddress)
at Microsoft.Diagnostics.Runtime.Linux.LinuxLiveDataReader.GetVersionInfo(UInt64 baseAddress, VersionInfo& version)
at Microsoft.Diagnostics.Runtime.ModuleInfo.get_Version()
at …
```
=> Don't throw NRE from MemoryVirtualAddressSpace.Name, return null instead

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStringType.cs
The data for System.String is not present in triage dumps, but ClrMD assumes we can always construct some basic types including System.String.  This change creates a "fake" string type when we cannot create the type for String specifically.
Fixes https://github.com/microsoft/clrmd/issues/860.
=> Fix triage dumps

src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs
DacDataTargetWrapper would cache a module list that wasn't cleared when Flush is called.  Now we allow ClrRuntime.Flush to also flush DacLibrary -> DacDataTargetWrapper.
Fixes https://github.com/microsoft/clrmd/issues/856.
=> Ensure DacDataTargetWrapper is flushed

src/Microsoft.Diagnostics.Runtime.Tests/src/DACNameParserTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/DACNameParser.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStringType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs
Reimplement DAC name parsing to handle nested classes of generic classes and a bunch of other corner cases (+ tests for same)
=> Reimplement DAC name parsing

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs
When analyzing a dump for a x86 program, I faced a division by zero exception when calling ClrSegment.GetNextObjectAddress.
```
at Microsoft.Diagnostics.Runtime.Implementation.ClrmdSegment.GetMarkerIndex(UInt64 obj)
at Microsoft.Diagnostics.Runtime.Implementation.ClrmdSegment.GetNextObjectAddress(UInt64 addr)
at Microsoft.Diagnostic.Tools.Dump.ExtensionCommands.ClrMDHelper.<EnumerateObjectsInGeneration>d__37.MoveNext() in C:\dev\dotnet-diagnostics\src\Tools\dotnet-dump\ExtensionCommands\ClrMDHelper.cs:line 710
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
```
It occurs because my current segment is only 16 bytes long, with a "free" ClrObject" occupying 12 out of the 16 bytes. (The exception happens the second time I call GetNextObjectAdddress, with `<segmentAdress> + …
=> Fix division by zero exception when segment length is <=16 bytes

src/Microsoft.Diagnostics.Runtime/src/Common/ObjectSet.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CacheEntryBase.cs
When opening a large memory dump file (10+ GB), any segment that is larger than 2GB in size is missing.
This is because an arithmetic overflow occurs when both loading the dump and again when creating the runtime.
Loading the same dump file in ClrMd 1.1 works fine so I suspect this is a regression.
Having the segments missing means that walking the heap objects and enumerating the roots will not return the correct data.
=> * Handle arithmetic overflow when dealing with large memory dump files.

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs
We don't actually know (or have a good way to get) the layout of images.  We'll use the "_isVirtual" flag as a first try, and if it fails we fall back to the other layout.
Fixes https://github.com/microsoft/clrmd/issues/891.
=> Try both PE image layouts

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeHelpers.cs
ClrmdArrayType.GetArrayElementAddress can return a wrong address.
The method calls Helpers.GetObjectData and expect it to return a nullable value but in the current implementation it's always not null. This behavior can lead to incorrect calculation of an element address.
=> Fix: ITypeHelpers.GetObjectData should return a nullable value

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
Bring async pinned handles into line with ClrMD 1.1 behavior.
Contributes to https://github.com/microsoft/clrmd/issues/881.
=> Enumerate inner async pinned handles

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/ModuleBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataModule.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleData.cs
Add a ICLRRuntimeLocator impl to DAC data target so single-file runtime can be found.
Fix single-file module names. The DAC GetPEFileName() GetAssemblyName() don't return a module/assembly file path for single file apps.
=> More single-file fixes

src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs
Currently, ```DbgEngDataReader.PointerSize``` returns ```IntPtr.Size``` instead of the pointer size of the dumped process.
Fixed.
=> DbgEngDataReader.PointerSize should return the pointer size of the dumped process

src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/x86_thread_state64_t.cs
This allows us to walk through the stack on macOS.
Related issue: #888
The changes for macOS ARM64 will be in a different PR.
=> Implement IDataReader.GetThreadContext() for MacOSProcessDataReader

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComCallableIUnknown.cs
This allows wrappers that use ComCallableIUnknown to clean up any
internal state on ref count == 0.
=> Add Destroy() override to ComCallableIUnknown

src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/arm_thread_state64_t.cs
Also adds arm_thread_state64_t struct for the case when ptrauth is disabled.
Related issue: #888
Based on #915, review it first pls.
=> Add support for macOS ARM64 in MacOSProcessDataReader

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfDynamicSection.cs
Not all of memory for the export symbols existing for every module in a core dump
generated by createdump. Only the runtime module is guaranteed. These read memory
IO exceptions being thrown by GnuHash.GetPossibleSymbolIndex or SymbolTable.GetSymbol
reading the hash table or the symbol entry itself.
=> Fix escaping IOExceptions from TryLookupSymbol

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs
Put back try/catch to CoreDumpReader.TryGetSymbolAddress (was removed in 4f366cb Expose ELF coredump reader as public). Some dumps can't be opened without it.
=> Fixed microsoft#931. IOException when importing some of the core dumps

src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/SegmentBuilder.cs
This PR fixes https://github.com/microsoft/clrmd/issues/936.
To get our terminologies straight, while we still have the `heap_segment` objects, we call them `region` objects under the context of `USE_REGIONS`. 
Under `USE_REGIONS`, the `heap_segment` object itself is stored somewhere other than the address it manages (it is part of the `seg_mapping_table` to be precise), therefore we cannot use the address of the `heap_segment` object itself to determine the base address of the region.
With `USE_REGIONS`, gen0 and gen1 are no longer restricted on `ephemeral_heap_segment`, we could have a linked list of regions for gen0 and gen1. This explains the extra calls to `AddSegments` on `ProcessHeap`.
The field `allocation_start` is no longer defined in `generation`. For backward compatibility …
=> Support regions

src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntry.cs
Fixed arithmetic overflow that happens for some big dumps.
=> Fixed arithmetic overflow

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs
This fixes what a problem with my previous single-file module fix. The hacky MacOS ELF dumps that 5.0 generates (6.0 now generates actual MachO dumps) have modules with no PageOffset == 0 file entries so my previous change doesn't add them to the list of modules.
=> Fix .NET 5.0 MacOS ELF dump module list

src/Microsoft.Diagnostics.Runtime.Tests/src/PEImagePdbTests.cs, src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IExportReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/RelativeAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCoreDump.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageExportDirectory.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
Added PEImage.TryGetExportSymbol public method.
Clean up and refactor of ELF symbol export lookup. Added ElfFile.TryGetExportSymbol public method.
Added ElfFile constructor that allows a memory stream to be passed.
Added IExportReader implementation to MinidumpReader and DbgEngDataReader.
=> Add IExportSymbols support to PEImage modules

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/RelativeAddressSpace.cs
With certain linux dumps, dotnet-dump hit a problem because the ulong _length conversion to int caused the if to incorrectly Slice the buffer which threw an ArgumentOutOfRangeException.
=> Fix int overflow on certain large ELF modules 

src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs
Fix memory corruption of target process in MacOSProcessDataReader.LoadThreads()
Previously it accidentally used mach_vm_deallocate() on the target process's memory
but not our own, causing EXC_BAD_ACCESS (SIGSEGV) after the process detached.
=> Fix memory corruption of target process in MacOSProcessDataReader.LoadThreads()

src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs
Load memory regions after process suspend in MacOSProcessDataReader
Fixes a race condition when the target process's memory regions are modified before the process suspended.
=> Load memory regions after process suspend in MacOSProcessDataReader

src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOModule.cs
Change the symbol export lookup to first search the exports and then all the symbols.
=> Fix reading dumps from MacOS version 12 or greater (Monterey)

src/Microsoft.Diagnostics.Runtime.Tests/src/ClrDelegateTests.cs, src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDelegate.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDelegateTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/TestTargets/Types/Types.cs
- Added ClrObject.IsDelegate and ClrObject.AsDelegate.
- Added ClrDelegate view over a target delegate object to enumerate the methods that would be called when a delegate is invoked (along with their targets).
- Added a few ClrObject helpers for fields, "TryRead*"
=> Delegate targets

src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CacheEntryBase.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CacheNativeMethods.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CachePage.cs
Fix for #947.
Mini Dump can have large segments. Currently, unit is used to store the size of a segment and it might be not enough in some cases. In particular, I have a dump of IIS process that has a large (more than 8Gb) segment. When I'm trying to analyze it with ClrMD it crashes with System.AccessViolationException.
=> Mini Dump segment size might be bigger than Int32 can fit

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs
The unhandled exception in the ELF reader happened because there is a duplicate file pointer
entry for some images in the list. Removed the unnecessary ElfLoadedImage file table list
and tracked the minimum pointer instead. This is the symstore ELF reader does and it works
great.
Issue: https://github.com/dotnet/diagnostics/issues/3003
Passes the SOS tests.
=> Fixes crash with ELF alpine arm32 dump

src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs
Only check for the single file export if we have a high likelihood of succeeding.
=> Improve non-single file perf

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
A faster version of EnumerateReferences, if you don't need the type.
=> Add ClrObject.EnumerateReferenceAddresses

src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs
The com wrappers steal references, need to AddRef them to ensure we don't over Release.
=> Fix refcount problem

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComCallableIUnknown.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/UnknownVTable.cs
Partially fixes #1015
@leculver should I also change all `delegate\* unmanaged.*HResult>` entries? 
<details> <summary> `delegate\* unmanaged.*HResult>` entries </summary>
```
src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugControl.cs:        public readonly delegate* unmanaged[Stdcall]<IntPtr, out uint, out DEBUG_CLASS_QUALIFIER, HResult> GetDebuggeeType;
src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugControl.cs:        public readonly delegate* unmanaged[Stdcall]<IntPtr, HResult> IsPointer64Bit;
src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugControl.cs:        public readonly delegate* unmanaged[Stdcall]<IntPtr, out IMAGE_FILE_MACHINE, HResult> GetEffectiveProcessorType;
src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugControl.cs:        public readonly delegate* …
```
=> Change IUnknownVTable.QueryInterface return type from HResult to int

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs
Reverts microsoft/clrmd#1023.
This simply does not work.  Even in a reasonable heap dump (not mini or triage dump) there are "holes" in memory where the file is laid out into memory.  These holes result in bad reads, so you can't use this stream for standard PE reading libraries.  I may bring this back in some other form, but for now I'm not shipping this until I can think through a better way to do it.
=> Revert "Implement ModuleInfo.TryOpen"

src/Benchmarks/AweHelpers.cs, src/Benchmarks/Benchmarks.csproj, src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
- Move benchmarks to .Net 6.
- Update Shipped/Unshipped api surface now that we are on 2.2.
- Fix SupportedOSPlatform warning.
=> Minor cleanups for 2.2

src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/SegmentBuilder.cs
@Maoni0 reported that generational aware analysis in PerfView is not working for full core dumps. After debugging for a while, I have found a few bugs related to generation detection. This PR fixes some of them, the remaining ones are in PerfView and are fixed [there](https://github.com/microsoft/perfview/pull/1674).
With this change, we have these new invariants for regions, which used to hold for segments.
```
Gen2Start == Start
Gen2Start + Gen2Length == Gen1Start
Gen1Start + Gen1Length == Gen0Start
Gen1Start + Gen0Length == End
```
The old code is not *technically* wrong, the ranges are empty anyway, but this is more convenient for PerfView to consume, and we don't know if there are other tools replicated the way PerfView did things, so might as well get it fixed.
=> Fix a bug related to generation bounds for regions

src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageRelocation.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
When a `PEImage` is loaded because we are reading from a `DataTarget`, this change will perform the necessary relocation so that subsequent `PEImage.Read` will produce correct values as if it is loaded in memory in the process.
This is apparently incomplete (e.g. not handling all relocation types), but it is good enough in the sense that it can successfully initialize the DAC when the `coreclr.dll` image is not saved (e.g. created by `createdump.exe --with-heap` on Windows). 
Tested on x64 only.
=> Support PE relocation

src/Microsoft.Diagnostics.Runtime/src/Implementation/FileSymbolCache.cs
This change allows PerfView users to set the symbol path to the build folder and open Linux minidumps as follows:
`set _NT_SYMBOL_PATH = <runtime-repo-base>\artifacts\bin\coreclr\Linux.x64.Debug` 
The problem with the existing code is that it insists the crossdac must be exactly at the path generated by the `FindPEImage` method. In my example, the code checks if this file exists and fails the lookup if it isn't there.
```
<runtime-repo-base>\artifacts\bin\coreclr\Linux.x64.Debug\mscordaccore.dll\elf-buildid-coreclr-ee0b86c2c007c9cd8008ebb49c6bd22c8593ff74\mscordaccore.dll
```
I understand this is what a normal symbol cache would do, but it is so inconvenient that I prefer to have the symbol logic checking one more location.
=> Locate file directly

src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCoreDump.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOModule.cs
On Ventura, the dylinker header isn't on a segment boundary any more. It is usually 8K into segment. There were also problems with incorrectly calculating the LoadBias and the TryLookupSymbol result.
See: https://developer.apple.com/forums/thread/720064
Runtime issue: https://github.com/dotnet/runtime/issues/79355
=> Fix MachO core dump generated on the Ventura (13.0.1)

eng/Versions.props, src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrNativeHeapInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Common/NativeHeapKind.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac13.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IRuntimeHelpers.cs, src/Samples/DbgEngExtension/MAddress.cs
Added ClrRuntime.EnumerateClrNativeHeaps.  This function will enumerate the native heaps/memory that CLR has allocated.  This is intended to be used in functions similar to SOS's !eeheap.
Added ISOSDacInterface13 to implement this and related functions.
Worked around an issue in .Net 7.
=> Add a way to enumerate native heaps

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/NativeHeapKind.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac13.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/ModuleData.cs
We found more issues with native heap reporting, so we extended ISOSDacInterface13 to account for those missing heaps and to future-proof adding and removing heaps: https://github.com/dotnet/runtime/pull/82437.
This change updates ClrMD to account for the additional interface methods.
=> Re-implement ISOSDacInterface13

src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/RuntimeInfo.cs
Checks for the new version 2 of the RuntimeInfo added in .NET 8 containing the runtime version. 
I'm not sure if this is the best approach but I didn't want to read the whole new ClrRuntimeInfo2 without checking the version just in case on < 8 runtimes it is on a page boundary.
=> Use the RuntimeVersion in the new RuntimeInfo 2 for single file apps

src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/ObjectCorruption.cs
Differentiate between failing to read a MT, and MT corruption.
=> Change MT corruption message

src/Microsoft.Diagnostics.Runtime.Tests/src/VerifyHeapTests.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/ClrThinlock.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/ObjectCorruption.cs
- Added support for Thinlocks
- Fixed object mark MethodTable issue
- Fixed issue with Free objects being marked as too large
- Rearranged ObjectCorruptionKind enum, renamed some entries
- Check object header after validating members
=> Add thinlock support, ObjectCorruption cleanups

src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/ClrThinlock.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrHeapHelpers.cs, src/Samples/DbgEngStandalone/Program.cs, src/Samples/DbgEngStandalone/Properties/launchSettings.json
- Rename ClrThinLock
- Don't enumerate a thread when there isn't one.
=> ThinLock fixes

src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs
Eliminate null threads when GetThreadFromThinlockId fails or returns 0.
=> More thinlock fixes

src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrSegment.cs
Fix an issue where we would not properly enumerate ranges of objects.
=> Fix issue with EnumerateObjects(MemoryRange)

src/Microsoft.Diagnostics.Runtime/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrThreadHelpers.cs
There seems to be a bug in the dac when we pass a buffer less than the total amount of stack references or handles.
The original SOS C++ GCRoot code seems to have worked around it by finding the total number of entries and passing a buffer big enough to hold it.
=> Change how we walk stackrefs/handles

src/Microsoft.Diagnostics.Runtime/ClrGenerationData.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrOutOfMemoryInfo.cs, src/Microsoft.Diagnostics.Runtime/ClrSegment.cs, src/Microsoft.Diagnostics.Runtime/ClrSubHeap.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrGenerationData.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrHeap.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrOutOfMemoryInfo.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrSegment.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrSubHeap.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IObjectCorruption.cs, src/Microsoft.Diagnostics.Runtime/ObjectCorruption.cs
This should ensure that the interfaces for `IClrHeap`, `IClrSubHeap`, and `IClrSegment` match the public APIs of the corresponding classes.  Some new interfaces were required.
=> Ensure public interfaces have all the public APIs.

src/Microsoft.Diagnostics.Runtime/ClrSegment.cs, src/Microsoft.Diagnostics.Runtime/ClrSubHeap.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/Structs/HeapDetails.cs, src/Microsoft.Diagnostics.Runtime/GCSegmentKind.cs, src/Microsoft.Diagnostics.Runtime/Generation.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrSegment.cs
- Fix an issue with recent runtimes not properly reporting Finalizer roots.
- Change ClrSegment.GetGeneration to return an enum of what kind of generation the object belongs to.
- Re-order `GCSegmentKind` to match `Generation` ordering.
=> FinalizerRoots and Generations

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/GCRoot.cs
- Add a way to trace GCRoot operation
- Now produce a ClrObject instead of address in target predicate.
- Accept a CancellationToken.
=> GCRoot improvements

src/Microsoft.Diagnostics.Runtime/ClrException.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/Utilities/PEImage/ResourceEntry.cs, src/Microsoft.Diagnostics.Runtime/Windows/Minidump.cs
When there is an `if` in a copy loop `MoveToImmutable` throws IVO.  Use the existing extension method throughout for safety.
Partial stack is here:
```
System.InvalidOperationException: MoveToImmutable can only be performed when Count equals Capacity.
at System.Collections.Immutable.ImmutableArray`1.Builder.MoveToImmutable()
at Microsoft.Diagnostics.Runtime.Implementation.ClrHeapHelpers.GetSubHeaps(ClrHeap heap)
at Microsoft.Diagnostics.Runtime.ClrHeap.GetSubHeapData()
at Microsoft.Diagnostics.Runtime.ClrHeap.get_Segments()
at Microsoft.Diagnostics.Runtime.ClrHeap.Microsoft.Diagnostics.Runtime.Interfaces.IClrHeap.get_Segments()
at Microsoft.Diagnostics.Runtime.ObjectSet..ctor(IClrHeap heap)
```
=> MoveToImmutable can throw IVO if capacity != count.

src/Microsoft.Diagnostics.Runtime/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/ClrValueType.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrValue.cs
If you don't know the field name, then the `Try` version won't cause `ArgumentExceptions`.
=> Add TryReadStringField api similar to TryReadObjectField

src/Microsoft.Diagnostics.Runtime/ClrInfo.cs
Loading Linux single-file core dumps either with windbg or dotnet-dump on Windows doesn't work because the perf fix added in PR #1000 checked for the host/running OS not the target OS.
=> Fix Linux single-file apps dumps loaded on Windows

src/Microsoft.Diagnostics.Runtime/Implementation/ClrThreadHelpers.cs
I have a memory dump in which the following operation finds 2 frames:
```
ClrStackFrame? frame = stack.SingleOrDefault(f => f.StackPointer == stackRef.Source || f.StackPointer == stackRef.StackPointer && f.InstructionPointer == stackRef.Source);
```
The dump is apparently special but contains useful information. I believe that would be nice to still be able to list the roots from the stack.
=> Prevent exception when reading roots from the bad stack

src/Microsoft.Diagnostics.Runtime/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrThreadHelpers.cs
Remove some previous tracing used to track down a stackwalking issue.
This reverts commit e83385be84307b5f88f1d3582dfd9e25c0797664.
=> Remove some previous tracing

src/Microsoft.Diagnostics.Runtime/GCRoot.cs
When we fail to store an edge into the refList, we would "complete" the refList, but forgot to re-attempt to add the edge to the newly created list.
=> Fix issue where we miss an edge of the root graph

src/Microsoft.Diagnostics.Runtime/Implementation/ClrDacType.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrTypeHelpers.cs
The dac private API will return `<Unloaded Type>` for dynamic type names.  We can work around this by using metadata (when available) to produce the name.  This restores ClrMD 1.1's behavior.
Fixes https://github.com/dotnet/diagnostics/issues/4108.
=> Use metadata to find type names when appropriate

src/Microsoft.Diagnostics.Runtime.Tests/src/DACNameParserTests.cs, src/Microsoft.Diagnostics.Runtime/Implementation/DACNameParser.cs
Fix DAC name parser to deal with non-closed generic types and non-assembly qualified names (see bug #897).
Add lots of comments to parser as its complex due to having to deal with tragedies like the type name in the ParseGenericWithComplexGenericArgs2 test.
Replace uses of char literals in numerous places with their named constants I was using elsewhere.
Correct numerous comment spelling errors (thanks VS spell checker).
Add numerous tests both for the case in 897, some variants of it, and another case I encountered internally.
Add support for non-traditional generics as produced by FSharp and various obfuscators.
=> Fix bugs in DAC names that either contain non-closed generics or non-assembly qualified names

src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs
OOM data had inverted logic for Server/Workstation GC.
=> Fix OOM data issue

src/Microsoft.Diagnostics.Runtime/ClrThread.cs, src/Microsoft.Diagnostics.Runtime/Implementation/DacThreadData.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrThreadData.cs
Do a better job caching frames:
- Don't rely on a max number of frames internally, let the user break out of the loop.
- Cache frames only if the user didn't break out of the loop.
- Root enumeration still needs to cap the number of frames sensibly, but we won't interfere with the user's enumeration if we hit an internal limit.
Contributes to https://github.com/dotnet/diagnostics/issues/4209.
=> Better Frame Caching

src/Microsoft.Diagnostics.Runtime/Implementation/DacHeapProvider.cs
This was inadvertently reverted in a previous checkin.
=> Restore ISOSDac8 fix

src/Microsoft.Diagnostics.Runtime/ModuleInfo.cs
This allows the SOS infra to leverage the clrmd internal PEImage's resource code for use in its IDataReader impl.
=> Add ModuleInfo.TryCreateResourceRoot

src/Microsoft.Diagnostics.Runtime/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SymbolServer.cs, src/Microsoft.Diagnostics.Runtime/Linux/ElfSymbolGnuHash.cs
- Catch a stray AggregateException when a symbol server is not reachable.
- Prevent System.OverflowException from creeping out of `ElfFile.TryGetExportSymbol`.
- Generate a more helpful exception message when we encounter a bad dump file.
This is the exception message we generate when `CLRDataCreateInstance` fails with exception code 0x80131c4f:
Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: 'Failure loading DAC: CreateDacInstance failed 0x80131c4f, which usually indicates the dump file was taken incorrectly.'
While the root cause will not always be an incorrectly generated dump file, it is the right first thing to investigate.
=> Generate better exceptions with bad dump files

src/Microsoft.Diagnostics.Runtime/ClrThreadPool.cs
Updated to fill in the IO completion thread pool info when it exists.
=> Show IO completion thread pool info when the info is available and the portable thread pool is being used

src/Microsoft.Diagnostics.Runtime.Tests/src/MethodTests.cs, src/Microsoft.Diagnostics.Runtime/Implementation/DacTypeProvider.cs
The current implementation uses the CodeHeader based on the slot address, which does not provide the hot and cold region info for the method.
Instead use the MethodDesc's native address.
=> Get method's hot and cold region info based on the MethodDesc's native address

src/Microsoft.Diagnostics.Runtime/DacImplementation/DacTypeHelpers.cs
When walking FieldDescs, NumStaticFields already contains all thread static fields, so we should not add that value to the values to walk.
=> Fix an issue where we over-walk fields

src/Microsoft.Diagnostics.Runtime/AbstractDac/IAbstractThreadHelpers.cs, src/Microsoft.Diagnostics.Runtime/ClrThread.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacThreadHelpers.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ClrDataTask.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/DacDataTarget.cs
Only publish Trace statements in stackwalking when the failure is unexpected.
Closes #1223.
=> Clean up some Trace statements

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj
System.Collection.Immutable and System.Runtime.CompilerService.Unsafe both are included in .NET 6.0, so there is no need to reference their packages.
With it, dependent project will also not include that unneeded dependencies.
=> Make dependencies to System.Collection.Immutable and System.Runtime.CompilerService.Unsafe conditional

src/Microsoft.Diagnostics.Runtime/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/ClrValueType.cs
Remove boxing when calling ClrObject.ReadField<T> and ClrValueType.ReadField<T>.
Cast to object seems to be leftover from ClrMd v1, where ClrInstanceField.Read was not generic and returned an object.
Btw. I am unable to run the tests, I get an InvalidOperationException stating: "You must first generate test binaries and crash dumps using by running: dotnet build C:\projects\clrmd\src\TestTargets\TestTargets.csproj". But the csproj-file doesn't exist, so the command does nothing.
I am pretty sure my change is correct, but it would be nice with some documentation on how to build everything locally, so I can also run the tests :)
=> Remove boxing when calling generic ReadField method

src/Microsoft.Diagnostics.Runtime/AbstractDac/IAbstractMethodLocator.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/ClrType.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacMethodLocator.cs
The existing implementation is not able to get the method from an instantiated method handle or instruction pointer, as `type.Methods` only contains typical uninstantiated MethodDescs.
Change the way how we get ClrMethod to support getting instantiated method as well.
=> Fix the way of getting ClrMethod from method handle or instruction pointer

src/Microsoft.Diagnostics.Runtime/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeFactory.cs
For processes with numerous loaded modules, the overhead of fetching module information becomes prohibitively expensive. 
Introduce that population of module information is deferred until accessed.
A few minor changes was done to avoid triggering the load of module info.
Time measurements, of getting stack traces of a process with 200K modules loaded, showed a reduction of 9/10 of execution time.
=> Add deferred loading of module information for ClrModules

src/Microsoft.Diagnostics.Runtime/Linux/LinuxLiveDataReader.cs
I ran into a situation where createdump was able to read the memory of the crashing process but ClrMD failed with an `UnauthorizedAccessException`. After digging deeper, it looks like createdump fallbacks to reading `/proc/<pid>/mem` when `process_vm_readv` returns EPERM:
https://github.com/dotnet/runtime/blob/15e98e58e6023be3121dcb0ed2e701d1d5cd098e/src/coreclr/debug/createdump/crashinfounix.cpp#L514-L531
I don't actually know _why_ `process_vm_readv` fails (it's in an ARM64 CI agent running docker), but the fallback fixes it.
=> Implement /proc/pid fallback on Linux

azure-pipelines-external.yml
AzDO will remove macos-11 in about two weeks: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#recent-updates
Bump to macos-latest to match the internal build.
/cc @leculver
=> Bump to macos-latest build image

src/Microsoft.Diagnostics.Runtime.Tests/src/SymbolGroupTests.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SymbolGroup.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SymbolServer.cs
Fix bug where we did not properly respect the cache set in the symbol path.
=> Symbol cache cleanup/fixes

src/Microsoft.Diagnostics.Runtime.Tests/src/FileLocatorTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/CustomDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SymbolGroup.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SymbolServer.cs
Setting ClrMD_TraceSymbolRequests=1 will now produce Trace messages of all symbol server requests.
=> Add symbol tracing environment variable

src/Microsoft.Diagnostics.Runtime/MacOS/MachOModule.cs
`ReadSymbolTable()` will use `DataReader.Read()`
If `_symtab.NSyms` is `0` but it passed previous checks, `Read()` will assert.
Didn't remove the assert but add this check.
I don't know why but in a game some modules will cause the assert.
=> MachOModule.cs add bound check

src/Microsoft.Diagnostics.Runtime.Utilities/Microsoft.Diagnostics.Runtime.Utilities.csproj
Update utilities dependency version.
=> Version bump utilities dependency

src/Microsoft.Diagnostics.Runtime/Implementation/SymbolServer.cs
Fix authorization headers to not fail when we hit the first re-request for access tokens.
=> Fix authorization headers

src/Microsoft.Diagnostics.Runtime.Utilities/DbgEng/DbgEngIDataReader.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacThreadHelpers.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/DacDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Registers/LoongArch64Context.cs, src/Microsoft.Diagnostics.Runtime/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/Linux/IElfPRStatus.cs, src/Microsoft.Diagnostics.Runtime/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfHeaderCommon.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfMachine.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfPRStatusLoongArch64.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/RegSetLoongArch64.cs, src/Microsoft.Diagnostics.Runtime/Utilities/PEImage/ImageFileMachine.cs, src/Samples/DbgEngExtension/MAddress.cs
Add support for the new architecture LoongArch64.
* The `(Architecture)6` is `Architecture.LoongArch64`, which was introduced since .NET 7 and later.
@shushanhf
=> [LoongArch64] Add support for loongarch64 architecture

src/Microsoft.Diagnostics.Runtime/DacImplementation/DacServiceProvider.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosDac14.cs
Added ISOSDac14 support for .Net 9 statics.
Fixes https://github.com/dotnet/diagnostics/issues/4803.
=> Add ISOSDac14 for .Net 9 static variable support

src/Microsoft.Diagnostics.Runtime/DacImplementation/DacTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosDac14.cs, src/Microsoft.Diagnostics.Runtime/Extensions/ClrElementTypeExtensions.cs
- Followup to https://github.com/microsoft/clrmd/pull/1284, passed in the method table address to the statics APIs instead of the module address
- Treated `ClrElementType.Pointer` as primitive, as for thread-statics they seem to be stored in the non-GC section
=> Fix a couple of issues for statics in sos14

src/Microsoft.Diagnostics.Runtime/DacImplementation/DacThreadHelpers.cs
Adjust the offset values of SP and IP as well as the contextSize value in the EnumerateSackTrace function.
=> [LoongArch64] Fix the issue of incorrect printing information in the gcroot command

src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeFactory.cs
Try GetComponent for string always returns null. So this call can be skipped to improve performance.
=> Do not call TryGetComponentType for the string types

src/Microsoft.Diagnostics.Runtime/AbstractDac/IAbstractHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacHeap.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacServiceProvider.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ISOSDac16.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosDac16.cs
This PR is meant to support https://github.com/dotnet/diagnostics/issues/5090.
This PR is the clrmd side of the work, this exposes a new field so that the debugger can display the information.
There are two more PRs on different repos to support this:
On runtime: https://github.com/dotnet/runtime/pull/107115
On diagnostics: https://github.com/dotnet/diagnostics/pull/5164
=> Let the debugger knows DATAS is on

src/Microsoft.Diagnostics.Runtime/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/CustomDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/DacDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/DacDataTargetCOM.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/LegacyDacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/DebugLibraryKind.cs, src/Microsoft.Diagnostics.Runtime/IClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/Implementation/DotNetClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrInfo.cs, src/Microsoft.Diagnostics.Runtime/SymbolProperties.cs
Adds a new DebugLibaryKind.CDac enum used when the data contract export is found on a runtime module.
Currently the file path to the cdac is the same directory as the clrmd module.
Currently leaves it to the client (SOS in this case) to decide when it wants to instantiate the cdac. The standalone hosting support doesn't currently pick the cdac.
Breaking changes:
Add "bool verifySignature" to IClrInfoProvider.GetDacServices and remove the CustomDataTarget.DacSignatureVerificationEnabled property.
Adds data target support for ICLRContractLocator for when clrmd loads the cdac.
=> Add cDac runtime enumeration support

src/Microsoft.Diagnostics.Runtime/DataTarget.cs
I was writing a test that gave an invalid dump to DataTarget.LoadDump, and I noticed that the file stream wasn't closed. It looks like the condition has been wrong since it was originally added
=> Dispose dump file stream when leaveOpen is false
