src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/legacyruntime.cs, src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs, src/Microsoft.Diagnostics.Runtime/Desktop/v45runtime.cs, src/Microsoft.Diagnostics.Runtime/Native/NativeTypes.cs
Hit these bugs when I tried to integrate the serialized exception into PerfView.
=> Fixing a couple bugs in the serialized exception implementation

src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs
Fixes https://github.com/Microsoft/clrmd/issues/46
=> Fix stack walking on ClrStackFrame in x64

src/Microsoft.Diagnostics.Runtime/Desktop/runtimebase.cs
Addresses Issue https://github.com/Microsoft/clrmd/issues/61
=> Fix NullReferenceException in GetThreadByStackAddress()

src/Microsoft.Diagnostics.Runtime/datatarget.cs
=> Update DAC filename detection code in DataTargetImpl.ClrVersions

src/GCRootDemo/GCRootDemo.cs, src/GCRootDemo/GCRootDemo.csproj, src/GCRootDemo/Properties/AssemblyInfo.cs, src/GCRootDemo/app.config, src/Microsoft.Diagnostics.Runtime.Tests/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/Helpers.cs, src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/Targets/GCRoot.cs, src/Microsoft.Diagnostics.Runtime.Tests/TestTargets.cs, src/Microsoft.Diagnostics.Runtime.sln, src/Microsoft.Diagnostics.Runtime/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/GCCache.cs, src/Microsoft.Diagnostics.Runtime/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/ICorDebug/ICorDebugWrappers.cs, src/Microsoft.Diagnostics.Runtime/ICorDebug/IMetaHostWrappers.cs, src/Microsoft.Diagnostics.Runtime/MemoryReadException.cs, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/Native/NativeTypes.cs, src/Microsoft.Diagnostics.Runtime/ObjectSet.cs, src/Microsoft.Diagnostics.Runtime/datatarget.cs
Add an algorithm for GCRoot to ClrMD.
=> Add GCRoot to ClrMD

src/Microsoft.Diagnostics.Runtime/ClrObject.cs
ClrObjects are considered equal when point on same address.
=> ClrObject implements IEquatable, has operator overloads.

pkg/Microsoft.Diagnostics.Runtime.nuspec
=> Add xml to Microsoft.Diagnostics.Runtime nupkg

Documentation/GettingStarted.md
Make the code snippets compile against latest NuGet version 0.9.180305.01.
=> Make GettingStarted tutorial compile

azure-pipelines.yml
Now that we have approval, this will enable real-signed builds.
=> enable real signing!

Documentation/ClrRuntime.md
Mostly just typos and formatting, however I also updated the section that claimed AppDomain data was limited to just a few properties as you can now do quite a bit more with them.
`FinalizerQueue` was changed from a property to the method `EnumerateFinalizerQueueObjectAddresses()`, so the code sample was updated.
=> Formatting, typos and update some information

src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyDomainLocalModuleData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyObjectData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V2MethodDescData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V2ThreadPoolData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V35MethodDescData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V4ThreadPoolData.cs
=> fix order of fields in structs

Documentation/WalkingTheHeap.md
Enable syntax highlighting.
Consistent indentation.
Fix straggling closing braces.
=> Code block formatting

Documentation/TypesAndFields.md
Enable syntax highlighting.
Some typos and text layout for readability.
=> Formatting

src/Microsoft.Diagnostics.Runtime/src/Utilities/Symbols/SymbolLocator.cs
=> ability to customize SymbolLocator output

src/Microsoft.Diagnostics.Runtime/src/Common/RuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs
=> make DataTarget responsible for the ClrRuntime creation

src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopRuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs
=> Get name of JIT helper func / method table

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTargetImpl.cs
The current code forgot to prepend "lib" to the name of the DAC module.
=> Fix problem with DAC name on Linux.

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopMethod.cs
Fix DesktopMethod.IL returns null when DesktopModule.MetadataImport returns MetaDataImport, not IMetadataImport
=> Fix #217 DesktopMethod.IL returns null

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs
Failed when reading across contiguous adjacent segments in a core dump.
For example:
```
Type       Offset             VirtAddr           PhysAddr
FileSiz            MemSiz             Flags  Align
LOAD       0x000000000c62b000 0x00007ff76a9d0000 0x0000000000000000
0x0000000000010000 0x0000000000010000  RW     1000
LOAD       0x000000000c63b000 0x00007ff76a9e0000 0x0000000000000000
0x0000000000001000 0x0000000000001000  R      1000
LOAD       0x000000000c63c000 0x00007ff76a9e1000 0x0000000000000000
0x0000000000000000 0x000000000000f000         1000
```
In the ElfVirtualAddressSpace.cs Read function for  a 0x1000 count read at 0x00007ff76a9df9f0, the read
fails because the full read does fit in first or second segment but across both.
=> Fix ELF core dump reader's read memory.

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.xml, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs
I'm not sure why so much of the documentation XML file was regenerated. Should this file even be in version control?
=> Documentation tweaks

src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs
Lots of small commits to show what's going on. Hopefully they speak for themselves.
Part of drewnoakes/string-theory#7
=> GCRoot refactor

src/Microsoft.Diagnostics.Runtime/src/Common/ParallelObjectSet.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopHeapType.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/HandleRoot.cs
Part of drewnoakes/string-theory#7
=> Small bits

src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs
fixes https://github.com/Microsoft/clrmd/issues/238
You have CI so lets see what the serverbuild says :)
=> Fix #238: NullReferenceException when accessing Heap property

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs
inspired by https://youtrack.jetbrains.com/issue/DMRY-6581
dedicated exception can help to handle the case on the client side in a more graceful way.
=> Additional validation for proc addresses obtained from the dac library

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs
See issue https://github.com/dotnet/diagnostics/issues/360
=> Fix unhandled exception getting build id

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs
inspired by https://youtrack.jetbrains.com/issue/DMRY-6389
`DesktopGCHeap.GetTypeByMethodTable` can return nulls
=> Additional null checks in DesktopGCHeap

src/Microsoft.Diagnostics.Runtime/src/Common/VersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs
- make VersionInfo immutable
- provide IComparable, IEquatable, GetHashCode etc.
- simplify ClrInfo comparison
=> VersionInfo equality and comparison

src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
Because it uses System.Runtime.InteropServices.NativeLibrary.GetExport instead of TryGetExport
it throws an exception when the function can't be found instead of return null. This breaks
the DacLibrary init code (DacLibrary.cs line 86) when it is try to get the DAC_PAL_InitializeDLL
export and then the PAL_InitializeDLL export.
=> Fix LinuxFunctions.GetProcAddress throwing an exception

src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs
This seems to happen when we use 64-bit Task Manager to take a dump of a 32-bit process.
This may be the cause of the "strangely non-functional crash dumps" from taskmgr mentioned in https://github.com/microsoft/clrmd/pull/236#issuecomment-474482395
=> Ensure we get the module starting at the requested address in case of overlapping modules.

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Dump/MinidumpMemoryChunks.cs
=> Skip empty memory chunks when initializing

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/HeapBase.cs, src/Microsoft.Diagnostics.Runtime/src/Common/RuntimeBase.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac6.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/MethodTableCollectibleData.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopGCHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopHeapType.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/IMethodTableCollectibleData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/LegacyRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V45Runtime.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V46GCHeap.cs
Contributes to dotnet/coreclr#20166
=> Updates related to collectible AssemblyLoadContext

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Fixes https://github.com/microsoft/clrmd/issues/306
=> Stop attempting to parse version on Linux

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj
Leaving it on in side branches.
=> Diable FXCop for master

src/TestTargets/TestTargets.proj
Unrelated changes are separated by commits.
=> Enable incremental build on Windows

src/Microsoft.Diagnostics.Runtime/src/Common/ClrSegment.cs, src/Microsoft.Diagnostics.Runtime/src/Common/HeapSegment.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/SegmentData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/ISegmentData.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/V2SegmentData.cs
=> Add IsReadOnly on ClrSegment

src/Microsoft.Diagnostics.Runtime.Tests/src/DataTargetTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/NoFailContext.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TestTargets.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/TestTargets/Spin/Spin.cs, src/TestTargets/Spin/Spin.csproj
---
Removes `this` to conform to current styles. Personally I would prefer to prefix everything with `this`.
=> Improve LinuxLiveDataReader

doc/FAQ.md
Document resolution of #315 and include options for self-inspection
=> Document granting PTRACE access via prctl PR_SET_PTRACER option

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
The last permission field is either p or s.
=> Fix permission parser

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/TestTargets/Types/Types.cs
Added test to ensure that issue #108 is fixed in 2.0 and isn't regressed.
Closes https://github.com/microsoft/clrmd/issues/108.
=> ComponentTypeEventuallyFilledTest

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/TestTargets/Shared/SharedLibrary.cs, src/TestTargets/Types/Types.cs
Fixes https://github.com/microsoft/clrmd/issues/101.
=> Fix struct field size

src/.editorconfig, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs
Test case for https://github.com/microsoft/clrmd/issues/298.
=> String empty

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
- Wrap heap logging into its own function.
- Stop using MemoryReader for the large object heap.  Objects on the LoH are 85,000 bytes or more, so we don't need to read an entire chunk of memory just for the MethodTable and array count.
=> Clean up ClrmdHeap data reading

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs
IXClrDataProcess::Flush is unfortunately not wrapped with DAC_ENTER.This means that when it starts deleting memory, it's completely unsynchronized with parallel reads and writes, leading to heap corruption and other issues.  This means that in order to properly clear dac data structures, we need to trick the dac into entering the criticalse ction for us so we can call Flush safely then.
To accomplish this, we set a hook in our implementation of DacDataTarget::ReadVirtual which will call IXClrDataProcess::Flush if the dac tries to read the address set by MagicCallbackConstant.Additionally we make sure this doesn't interfere with other reads by 1) Ensuring that the address is in kernel space, 2) only calling when we've entered a special context.
=> Fix unsynchronized IXClrDataProcess::Flush corruption

src/Microsoft.Diagnostics.Runtime.Tests/src/ExceptionTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs
See dotnet/coreclr# 27575 for backgrounds.
=> Stop using Nullable<T>.Value

src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/WindowsFunctions.cs
=> Throw ArgumentException if the process is not running

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCDesc.cs, src/Microsoft.Diagnostics.Runtime/src/Common/MemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IMemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdMethod.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdThread.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ValueReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/MemoryVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
Fixes https://github.com/microsoft/clrmd/issues/409.
=> Fix MemoryReader leak

src/Microsoft.Diagnostics.Runtime.Tests/src/DataTargetTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
=> Throws InvalidDataException in DataTarget

src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs
Fixes https://github.com/microsoft/clrmd/issues/440.
=> Ensure modules are only enumerated once

src/Microsoft.Diagnostics.Runtime.Tests/src/PdbTests.cs
Fixes https://github.com/microsoft/clrmd/issues/434.
Filed https://github.com/dotnet/diagnostics/issues/708 to track underlying issue.
=> Make PDB test pass

src/Microsoft.Diagnostics.Runtime/src/Builders/ModuleBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/CollectionHelpers.cs
Partial fix for #438
At least it produces some results now.
=> Use loaded image base in module size dictionary

src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs
Change a few more ulong addresses to ClrDataAddress.
Rename delegates to match the new signature.
=> Fix a few more ulong address issues

src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfProgramHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/MemoryVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfProgramHeaderAttributes.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/FileVersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
Not the cleanest implementation with array allocation but it's functional enough for 1.1.
=> Backport VersionInfo change to 1.1

src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/FileVersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
Fixes https://github.com/microsoft/clrmd/issues/450.
=> Implement ModuleInfo.Version on Linux

src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/COMIMAGE_FLAGS.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/CorHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/CvInfoPdb70.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_COR20_HEADER.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_COR20_HEADER_ENTRYPOINT.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_DATA_DIRECTORY.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_FILE.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_OPTIONAL_HEADER_AGNOSTIC.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_OPTIONAL_HEADER_SPECIFIC.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/IMAGE_SCN.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageDebugDirectory.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageDebugType.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageFileHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageFileHeaderStruct.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageOptionalHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageOptionalHeader64.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageOptionslHeader32.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageSectionHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/SectionHeader.cs
=> Revert "Initial works on reimplementing PEImage using S.R.PE.PEReader"

src/Microsoft.Diagnostics.Runtime/src/Extensions/MemorySearcher.cs
#462 
Not all memory pages are present in dump files. The coredump reader now fails to find versions of native modules because the first RW LOAD segment of the module isn't placed in the coredump and therefore the memory searcher stops on the first read operation.
See the original implementation:
https://github.com/microsoft/clrmd/blob/429070b994d605e46aca8483e83e3061ac67259d/src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs#L120-L125
Alternatively we may tell the searcher where to skip by exposing the memory page information from the readers, which can be obtained from ELF program headers or `/proc/<pid>/maps` on Linux or `VirtualQuery` on Windows, if this will bring large perf improvements. (ETW is currently broken on my machine so I'm hesitant about perf …
=> Fix MemorySearcher

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs
All but one test seems to be passing.  I may have broken it in a previous checkin.  Won't get back around to look at this until tomorrow morning.
=> Enable tests

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
A first step to enabling live attach on Linux ARM/ARM64. GetThreadContext() may need some rework in future...
=> ARM support for LinuxLiveDataReader

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs, src/TestTargets/Arrays/Arrays.cs, src/TestTargets/Types/Types.cs
=> Add ClrArray.Rank

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandle.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackFrame.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRootPath.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStackFrame.cs
Fixes https://github.com/microsoft/clrmd/issues/459.
The underlying issue turned out to just be a test problem.  However, I found a few unrelated issues along the way and added some documentation.
=> Fix intermittent gcroot test failures

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs
=> Add ClrArray.GetLength(int)

src/Microsoft.Diagnostics.Runtime.Tests/src/BasicArrayTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdConstructedType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdPrimitiveType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/TestTargets/Types/Types.cs
Closes #488
Please review the API shapes before I start working on them.
=> Improve ClrArray, add multi-dimensional APIs

global.json, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDiagnosticsException.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrEnum.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxDefaultSymbolLocator.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/NullableAttributes.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Command/Command.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/CvInfoPdb70.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ImageSectionHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
Only one warning left.
Do we want to ensure non-null return here?
https://github.com/microsoft/clrmd/blob/fb1fa753c54e35e3468612d8b6f27843c70619f3/src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs#L192-L196
=> Add .NET Core 3.1 TFM

src/Microsoft.Diagnostics.Runtime.UnitTests/src/ClrObjectTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrEnum.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs
[Handling and throwing exceptions in .NET](https://docs.microsoft.com/dotnet/standard/exceptions/index)
Those exceptions should only be thrown by the runtime.
=> Don't throw NullReferenceException

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrFinalizerRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandle.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandleKind.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandleKindExtension.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRootKind.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRootKindExtension.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRootPath.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHandle.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRefCountedHandle.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs
- What does these `@` characters mean?
https://github.com/microsoft/clrmd/blob/f3c50ff41e49aeb9160cf0d8c17ca8dcf46200ff/src/Microsoft.Diagnostics.Runtime/src/Common/ClrHandle.cs#L49
- Don't you feel these names (#318) are more readable?
=> Update handle names

src/Microsoft.Diagnostics.Runtime.Tests/src/Helpers.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/FieldBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/MethodBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/TypeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrEnum.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrField.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrMethod.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/Helpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdConstructedType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdMethod.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdPrimitiveType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdStaticField.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IFieldData.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IFieldHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IMethodData.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeData.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeFactory.cs
To be signed `int`. https://github.com/microsoft/clrmd/issues/408#issuecomment-564673840
Doesn't touch struct fields.
=> Unify metadata token types

src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
I'm not satisfied with the implementation, but it's a little better.
What's your plan to rewrite the readers with `MemoryMappedFile`?
=> Improve Linux readers

azure-pipelines.yml
Simplify some logic and make sure the appropriate pool provider is used in all cases.
=> Fix choice of pool providers to properly match internal/public

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj, src/Microsoft.Diagnostics.Runtime.Tests/src/Debugger.cs, src/TestTargets/TestTargets.proj, src/TestTasks/TestTasks.csproj, src/TestTasks/src/Debugger.cs, src/TestTasks/src/Dump.cs
=> Bring back debugger for testing

src/Microsoft.Diagnostics.Runtime/src/Builders/SegmentBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataAddress.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac6.cs
Potentially fixes https://github.com/microsoft/clrmd/issues/402.
=> Sign extend arguments

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/WindowsFunctions.cs
Fixes #521 
Core libraries only use the new versions.
=> Switch to PSAPI_VERSION 2

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs
=> Fix element types for class types

src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopHeapType.cs
We previously would cache whether a type was an RCW/CCW which in theory should work.  However, the dac private API only allows us to query for CCW/RCW results per object.  This means that sometimes when an object that was a CCW was already cleaned up, we'd mark the type permanently as not being a CCW when it was.  This lead to future calls to IsCCW/GetCCW to fail.
=> Stop caching RCW/CCW results

src/Microsoft.Diagnostics.Runtime/src/Common/VersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Live/LiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSymbols.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/FileVersionInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs
=> Expose VersionInfo constructor

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfPRStatusX86.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/RegSetX86.cs
See dotnet/diagnostics#846 for background.
=> Unblock Linux x86 support

src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataMethod.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataModule.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataTask.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrStackWalk.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac6.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs
See https://github.com/dotnet/diagnostics/issues/846#issuecomment-604231358
Thanks @swift-kim
=> Use WINAPI calling convention for DAC APIs

src/Microsoft.Diagnostics.Runtime.Native/src/DacInterface/SosNative.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataMethod.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataTask.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrStackWalk.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetaDataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac6.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosStackRefEnum.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Desktop/HandleTableWalker.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/CallableComWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/VTableBuilder.cs
See https://github.com/dotnet/diagnostics/issues/846#issuecomment-606996179
=> [v1] Use WINAPI calling convention for native APIs

src/Microsoft.Diagnostics.Runtime.Tests/Microsoft.Diagnostics.Runtime.Tests.csproj
This reverts commit a4784a35124281899b0262d957e88feb2888403e.
=> Revert "Temporarily disable test asset building (#572)"

Directory.Build.props, Directory.Build.targets, azure-pipelines.yml
This reverts commit 9ba5fbf323d24c2719c4cae6aa8b96b377ab5a02.
Disabling code coverage did not fix the build issues.
=> Revert "Temporarily disable code coverage (#592)"

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
=> Fix module path resolution on Linux

src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrEnum.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCDesc.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ObjectSet.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/BinarySearchExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
Fixes https://github.com/microsoft/clrmd/issues/605.
=> Use named tuples and remove IReadOnlyList usage

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs
Also changed ClrObject.ReadBoxed to ReadBoxedValue.
=> Add ClrObject.IsBoxedValue

src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs
- Set a maximum number of children/name length to avoid long loopin over data.
- Users can change these defaults via static variables.
- Now track "ChildCount" separately from Children.Count.
- Check whether memory reads succeeded or not.
Fixes https://github.com/microsoft/clrmd/issues/564.
=> Handle corrupted PEImage resources better

src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs
Fix issues with ResourceEntry and ImmutableArray.
=> Various fixes

src/Microsoft.Diagnostics.Runtime.Tests/src/ModuleTests.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs
We could not round trip EnumerateTypeDefToMethodTableMap <-> ResolveToken becasue we did not set the flag for typeDefs.  Added tests to assert this works.
=> EnumerateTypeDefToMethodTableMap should set the mdtTypeDef bit

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
The original pattern looks odd.
=> 'try-finally' -> 'try-catch'

src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
PEReader can throw a BadImageFormatException when attempting to read PEHeaders.
=> Handle BadImageFormatException

src/Microsoft.Diagnostics.Runtime.Tests/src/BasicArrayTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/CacheOptionsTest.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/FieldTests.cs, src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueType.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/IAddressableTypedEntityExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdConstructedType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdPrimitiveType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs
To match `GetStaticFieldByName`.
=> GetFieldByName -> GetInstanceFieldByName

src/Microsoft.Diagnostics.Runtime.Tests/src/BasicArrayTests.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs
=> Implement partial array read

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
CA2000 is a really odd analyzer.
=> Merge exception codes

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs
It was a mistake to filter out the managed assemblies out of the ELF reader module list because there are coredumps generated with gdb running .NET Core 2.1.x with a stack overflow test that seems to have a bug or missing memory region where the ELF module can't be opened (ElfLoadedImage.Open() returns null). This causes most of the native modules (especially libcoreclr.so) to be missing. With this fix most dotnet-dump/SOS commands will work on this coredumps.
This is an regression caused by my module filtering change (sorry about that).
=> Don't filter out managed assemblies in Linux data reader.

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/WindowsFunctions.cs
`Failed to load dac: 0`
`Failed to load dac: blah blah blah`
=> Fix error messages of loading library

src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs
=> Create directory before creating file

src/Microsoft.Diagnostics.Runtime.Tests/src/MemoryReaderTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/StringReader.cs, src/Microsoft.Diagnostics.Runtime/src/Common/MemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ReadVirtualStream.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IMemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Extensions/MemorySearcher.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdArrayType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/MemoryVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/MinidumpMemoryReader.cs
=> IMemorReader.Read should return bytes read

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs
Occasionally we encounter a type where the reported MethodTableData.ParentMethodTable is non-null but invalid.  I'm not sure what causes that.  When we encounter these, it causes the field enumeration to fail because it will return the wrong fields for this type.  In these cases we'll just say there's no fields for that type since we cannot enumerate them correctly anyway.
Fixes this from #416:
> Getting fields for a type can throw IndexOutOfRangeException
=> Fix IndexOutOfRangeException when getting fields

src/Microsoft.Diagnostics.Runtime.Tests/src/MethodTests.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/CcwBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RcwBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/FieldInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/ObjectData.cs
A few dac structs still had their old names from ClrMD 1.1 days.
=> Rename a few dac structs

src/Microsoft.Diagnostics.Runtime.Tests/src/GCRootTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/GCRoot.cs
Fixes https://github.com/microsoft/clrmd/issues/459#issuecomment-634562070
=> Fix GCRoot in parallel mode

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCommand.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCommandType.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCpuArch.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCpuType.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOHeader64.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOSection64.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOSegmentCommand64.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/CoreFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/LinuxFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/MacOSFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/PlatformFunctions.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/WindowsFunctions.cs
=> Implement platform functions on osx-x64

global.json, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
Issue: https://github.com/microsoft/clrmd/issues/698
Added 3.1.0 runtime to global.json so the tests can run.
=> Add Linux symlink temp directory cleanup.

src/Microsoft.Diagnostics.Runtime.Tests/src/DataTargetTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MacOSDefaultSymbolLocator.cs
Contributes to #697
<details>
<summary>
Test program
</summary>
```cs
using System;
using System.Diagnostics;
using System.Linq;
namespace Microsoft.Diagnostics.Runtime
{
class Program
{
static void Main()
{
using var dt = DataTarget.AttachToProcess(Process.GetCurrentProcess().Id, false);
foreach (ModuleInfo m in dt.EnumerateModules())
{
Console.WriteLine(m);
}
Console.WriteLine(new string('-', 80));
var clr = dt.ClrVersions.Single();
using var rt = clr.CreateRuntime(clr.DacInfo.LocalDacPath!, ignoreMismatch: true);
foreach (ClrModule m in rt.EnumerateModules())
{
Console.WriteLine(m);
}
Console.WriteLine(new string('-', 80));
foreach (ClrObject obj in rt.Heap.EnumerateObjects())
{
// NOT Console.WriteLine(obj); due to ClrObject's implicit ulong conversion operator …
```
=> Implement minimal macOS process reader

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Even `pid_t` is defined as signed.
=> Process ID should be signed

src/Microsoft.Diagnostics.Runtime.Tests/src/ExceptionTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrException.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrObject.cs
=> Make ClrException a class

src/Samples/DumpHeap/DumpHeap.cs
@leculver Have fixed 2 bugs, one in the If statement and also header formatting.
Additionally have changed the output to be similar to !sos.dumpheap
Do let me know if there is anything else to be taken care of.
Sample Output at the bottom is from IISExpress running ASP.NET Core default website used for testing.
=> Bug Fix and output updated to be same as !sos.dumpheap

eng/Versions.props
=> Update version to 2.0 for RTM

src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/HeapSegmentDataCache.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/SegmentCacheEntry.cs
Fixes https://github.com/microsoft/clrmd/issues/727.
=> Fix for AWE oom

src/Microsoft.Diagnostics.Runtime.Utilities/Microsoft.Diagnostics.Runtime.Utilities.csproj
Unclear why CI is failing, temporarily disable these files.
=> Disable compiling two extension methods due to CI failure

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/LinuxSnapshot/LinuxSnapshotTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntryFactory.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CachedMemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/Minidump.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/UncachedMemoryReader.cs
=> Create DataTarget by Stream

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs
=> ClrType.EnumerateInterfaces should not throw an exception for System.String

Microsoft.Diagnostics.Runtime.sln, src/Benchmarks/AweHelpers.cs, src/Benchmarks/Benchmarks.csproj, src/Benchmarks/ParallelHeapBenchmarks.cs, src/Benchmarks/ParallelThreadRunner.cs, src/Benchmarks/Program.cs
Add initial benchmark for heap walking.
=> Add initial benchmark test

src/Microsoft.Diagnostics.Runtime/src/Windows/AWEBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/ArrayPoolBasedCacheEntry.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CacheEntryBase.cs
This change greatly reduces GC pressure in the cache along common read paths.
**Overview:** The old code to read data off a page was shared between GetDataForAddress (where we know how much data we want) and GetDataFromAddressUntil (where we don't). To accomplish this it indirected the actual reading of the data through an Action passed to it. Then each caller would create a lambda to pass in for the action that would accomplish their specific style of read.
**Problem:** This worked for what it intended, but perf profiling showed it had the (obvious but) unintended side-effect of creating lots of short-lived objects (the lambda + the Action wrapper for the lambda) that put a lot of pressure on the GC. A single call was not bad, millions of calls was very bad.
**Solution:** We trade off …
=> Greatly lessen GC pressure along hot path in heap segment cache reading

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/Structs/SosDac8.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeHelpers.cs
Contributes to dotnet/runtime#11157
=> Add ClrType.AssemblyLoadContextHandle

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs
Fixes #774.
This is one way to fix it.  Let me know if you prefer another approach.
=> Fix 32-bit CoreDumpReader to strip high bits of CLRDATA_ADDRESS

src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime.Utilities/ClrHeapExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Common/MemoryReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/CachedMemoryReader.cs
Fix an issue where we put the wrong variable through IDataReader.Read.
=> Fix heap walking regression

src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdType.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ITypeHelpers.cs
=> Rename AssemblyLoadContext{Handle -> Address}

src/Microsoft.Diagnostics.Runtime/src/Common/ClrArray.cs
Fixes the second issue in #786.
> The second issue is related to the way the address of the item is retrieved via GetValue. Since this method is checking the size of T (here UIntPtr) against the size of the item instance, the check throws:
=> Fix ClrArray for object references

src/Microsoft.Diagnostics.Runtime/src/DbgEng/DebugSymbols.cs
=> Fix issue where DbgEngDataReader would return 0.0.0.0 for version

src/Microsoft.Diagnostics.Runtime/src/Extensions/ProcessReaderExtensions.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfVirtualAddressSpace.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/UncachedMemoryReader.cs
=> Fix overflow

src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServerLocator.cs
Fixes https://github.com/microsoft/clrmd/issues/835.
=> Fix bad timestamp on index path

src/Microsoft.Diagnostics.Runtime.Tests/src/StaticFieldTests.cs
Validates https://github.com/microsoft/clrmd/issues/857.
=> Add String.Empty static test

src/Microsoft.Diagnostics.Runtime.Tests/src/MinidumpTests.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Minidump/MinidumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/Windows/Minidump.cs
Fixes https://github.com/microsoft/clrmd/issues/855.
=> Implement MinidumpReader.ProcessId

src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataMethod.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrStackWalk.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/MetadataImport.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComCallableIUnknown.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/ComHelper.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/VTableBuilder.cs
- Cleaned up the delegate conversion pull request.
- Fixed compiler errors.
- Moved from passing arrays to passing pointers.
=> Cleanup delegates

src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/MacOSFunctions.cs
Fix cases where windbg/dbgeng returns the coreclr module not in lower case (i.e. CoreCLR.dll).
Fixed Apple Silicon/Issue https://github.com/microsoft/clrmd/issues/888
=> Fix a couple of SOS issues

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs
Using CreateSnapshotAndAttach could throw an exception in certain environments.  Calling Process.GetProcessById
can throw an ArgumentException, but the code would only catch/swallow Win32Exceptions.The Process.Kill call here
also is problematic because theoretically the process id could have been assigned to a new process at that point
and we would be killing an arbitrary process.  (In practice this probably wouldn't happen though.)
This change stops throwing exceptions here since we can't really do anything if PssFreeSnapshot fails and it
removes the Process.Kill call.  Instead we log a Trace message to any listener and return.
=> Don't throw during DataTarget.Dispose

src/Microsoft.Diagnostics.Runtime/src/Common/DACNameParser.cs
Wrap Dac name parsing in a try/catch.  Historically parsing all of the various type names has been a real pain point.  We need to fix the underlying exception but for now we'll wrap the method in a try/catch to ensure it doesn't unexpectedly throw.
Contributes to https://github.com/microsoft/clrmd/issues/897.
=> Catch exception when parsing dac names

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs
We need to set ContextFlags in the context buffer before we pass it to GetThreadContext.
=> Fix intermittent GetThreadContext failure

eng/Versions.props, src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataReaders/IExportReader.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/RuntimeInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfDynamicSection.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfProgramHeader.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfStringTable.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfSymbol.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfSymbolGnuHash.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfSymbolTable.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfDynamicEntry32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfDynamicEntry64.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfDynamicEntryTag.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfFileTableEntryPointers32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfFileTableEntryPointers64.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfFileTableHeader32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfSymbol32.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfSymbol64.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfSymbolBind.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/Structs/ElfSymbolType.cs
Add symbol export support to ELF reader. Add related structs and enums.
Clean up ELF program header creation
Add IExportReader interface
Update public API definitions
Add public RuntimeInfo/SingleFileRuntimeInfo property to ClrInfo
=>  Add single-file support for Linux

src/Microsoft.Diagnostics.Runtime/src/DataReaders/MacOS/MacOSProcessDataReader.cs
Related issue: #888
Based on https://github.com/microsoft/clrmd/pull/915, review it first pls.
=> Add IThreadReader interface impl for MacOSProcessDataReader

src/Microsoft.Diagnostics.Runtime/src/DataReaders/Windows/WindowsProcessDataReader.cs
=> Kill the process created by DataTarget.CreateSnapshotAndAttach

src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/PlatformFunctions.cs
=> Fix the check of DAC & CoreCLR versions when they are not versioned

src/Microsoft.Diagnostics.Runtime/src/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/src/Linux/ElfLoadedImage.cs
Verify that ELF image has a base address
=> Fix ELF the module base address for single file apps

src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DumpFileFormat.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCoreDump.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOCoreReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOFileReader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOModule.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/MachOSegment.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/DyldAllImageInfos.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/DyldImageInfo.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/DysymtabCommand.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/LoadCommandHeader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/LoadCommandType.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/MachHeader64.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/MachOFileType.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/MachOFlags.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/NList64.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/Segment64LoadCommand.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/SpecialThreadInfoHeader.cs, src/Microsoft.Diagnostics.Runtime/src/MacOS/Structs/SymtabCommand.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/Platform/MacOSFunctions.cs
Still requires some cleanup.  This checkin is to get a build into the system.
=> Add initial Mach-O coredump support

src/Microsoft.Diagnostics.Runtime.Tests/src/PEImageResourceTests.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrDiagnosticsExceptionKind.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs
- Mark ClrDiagnosticsExceptionKind obsolete.
- Fix resource name issue.
=> Minor fixes

src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs
Fixes https://github.com/microsoft/clrmd/issues/976.
=> Add missing SetThreadContext vtable entry

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/RuntimeInfo.cs, src/TestTargets/single-file/Program.cs, src/TestTargets/single-file/single-file.csproj
We would request the wrong long-name dac in the single file case.
Contributes to https://github.com/microsoft/clrmd/issues/988.
=> Dac single file request fixes

src/Microsoft.Diagnostics.Runtime/PublicAPI/net461/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/net5.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/src/DacInterface/SOSDac12.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacLibrary.cs
Fixes https://github.com/microsoft/clrmd/issues/983.
=> Handle global allocation context

src/Microsoft.Diagnostics.Runtime/src/Linux/LinuxLiveDataReader.cs
Address #762 on Linux. The issue should not be closed as the problem still requires investigation on Windows.
=> ptrace: attach to all threads

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs
Add a way to change the symbol path.
=> Add DataTarget.SetSymbolPath

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs
Add a way to read a stream from a module
=> Implement ModuleInfo.TryOpen

src/Microsoft.Diagnostics.Runtime/src/Implementation/SymbolServer.cs
Fix issue with redirecting symbol severs.
=> Fix redirection

azure-pipelines.yml
This reverts commit 70e72747e1334281b0342c08d53ccdd7773a06ef.
=> Revert "CodeQL (#1044)"

src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs
Stackalloc will overflow in the case of very large reads, so we use ArrayPool instead
=> Fixes to PEImage reads

src/Samples/DbgEngExtension/MAddress.cs
For some reason I put !analyze instead of !address in this code.
=> Documentation updates

src/Samples/DbgEngExtension/DbgEngExtension.csproj, src/Samples/DbgEngExtension/Exports.cs, src/Samples/DbgEngExtension/ExtensionMethods.cs, src/Samples/DbgEngExtension/FindPointersIn.cs, src/Samples/DbgEngExtension/GCToNative.cs, src/Samples/DbgEngExtension/Help.cs, src/Samples/DbgEngExtension/Help/findpointersin.txt, src/Samples/DbgEngExtension/Help/gctonative.txt, src/Samples/DbgEngExtension/Help/help.txt, src/Samples/DbgEngExtension/Help/maddress.txt, src/Samples/DbgEngExtension/MAddress.cs
Renamed some of the example commands and added a !dbgengextension.help for it.
This should be the final version of these commands, minus any improvements or bugs I need to fix in the future.
=> Rename example commands, add !help

src/Microsoft.Diagnostics.Runtime.Utilities/DbgEng/IDebugSymbols.cs, src/Microsoft.Diagnostics.Runtime.Utilities/DbgEng/Wrappers/IDebugSymbolsVtable.cs, src/Microsoft.Diagnostics.Runtime.Utilities/DbgEng/Wrappers/IDebugSymbolsWrapper.cs, src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfo.cs, src/Microsoft.Diagnostics.Runtime/src/Utilities/COMInterop/CallableComWrapper.cs
Added a few extra IDebugSymbols functions.
Refactored ClrInfo.CreateRuntime to allow for a self-constructed DacLibrary.  This was always the intent but I never actually built the function.
=> Dbgeng update

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt, src/Microsoft.Diagnostics.Runtime/src/Builders/ModuleBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrAppDomain.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrModule.cs, src/Microsoft.Diagnostics.Runtime/src/Common/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdAppDomain.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdModule.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdRuntime.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IAppDomainHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleData.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/src/Implementation/IRuntimeHelpers.cs
Still trying to find the right design/implementation
=> Rework enumerating native heaps

src/Microsoft.Diagnostics.Runtime.Tests/src/HeapTests.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrSegment.cs
- Improve heap enumeration for getting the next/prev object.
- Better implementation for enumerating ranges of heap memory.
=> More efficient heap enumeration for ranges

src/Microsoft.Diagnostics.Runtime/Implementation/ClrNativeHeapHelpers.cs
Retry loader heap traverse when we fail to get the right answer. This primarily fixes old SingleFile where we don't know the CLR version.
=> Retry loader heap traverse

src/Microsoft.Diagnostics.Runtime/ClrArray.cs, src/Microsoft.Diagnostics.Runtime/ClrDelegate.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrType.cs
Fixes some easy NotImplementedExceptions.
=> Fix NotImplementedExceptions on common types.

src/Microsoft.Diagnostics.Runtime/PublicAPI/net6.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt, src/Microsoft.Diagnostics.Runtime/src/Common/ClrValueType.cs
Fixes https://github.com/microsoft/clrmd/issues/1098
=> Mark ClrValueType's constructor public

src/Microsoft.Diagnostics.Runtime/ClrRoot.cs, src/Microsoft.Diagnostics.Runtime/ClrStackRoot.cs, src/Microsoft.Diagnostics.Runtime/ClrThread.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosDac.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrThreadHelpers.cs, src/Microsoft.Diagnostics.Runtime/Interfaces/IClrRoot.cs
- Expose ClrStackRoot again
- Extend IClrRoot to include what StackRoot contains
- Add register name/offset to ClrStackRoot
=> Expand stack roots

src/Microsoft.Diagnostics.Runtime/GCRoot.cs
Fixed an issue where we'd only consider this first object in a chain.
=> Fix GCRoot walk

src/Microsoft.Diagnostics.Runtime/GCRoot.cs
Temporary workaround while I chase this problem down.
=> Don't throw when duplicating link in GCRoot chain

src/Microsoft.Diagnostics.Runtime/DacInterface/SosHandleEnum.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrRuntimeHelpers.cs
Turns out, ISOSHandleEnum::GetCount is not implemented
=> Handle fixes

src/Microsoft.Diagnostics.Runtime.Tests/src/VerifyHeapTests.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrHeapHelpers.cs
Added a way to deeply verify objects and not just stop at the first issue encountered.
=> Add a way to deeply verify objects

src/Microsoft.Diagnostics.Runtime/ClrNativeHeapInfo.cs, src/Microsoft.Diagnostics.Runtime/ClrNativeHeapState.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ClrDataProcess.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/ISOSDac13.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SOSDac12.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SOSDac13Old.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosDac13.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/SosMemoryEnum.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/Structs/SosMemoryRegion.cs, src/Microsoft.Diagnostics.Runtime/DacLibrary.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrNativeHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/IClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/NativeHeapKind.cs
Updates ClrMD with improvements from PR https://github.com/dotnet/runtime/pull/84454.
=> Updates ClrMD for the new ISOSDac3 extensions

src/Microsoft.Diagnostics.Runtime/DataTarget.cs
We expect FileLocator to handle searching on disk for PE images.  However, if FileLocator is null (or just a non-standard implementation) we may miss files on disk that otherwise match what we are looking for.
=> DataTarget.LoadPEImage fails if FileLocator==null

src/Microsoft.Diagnostics.Runtime/AbstractDac/IClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/AbstractDac/IClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/AbstractDac/IClrTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/ClrGenerationData.cs, src/Microsoft.Diagnostics.Runtime/ClrHeap.cs, src/Microsoft.Diagnostics.Runtime/ClrOutOfMemoryInfo.cs, src/Microsoft.Diagnostics.Runtime/ClrRuntime.cs, src/Microsoft.Diagnostics.Runtime/ClrSegment.cs, src/Microsoft.Diagnostics.Runtime/ClrSubHeap.cs, src/Microsoft.Diagnostics.Runtime/Extensions/UnsignedToSigned.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrDacType.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrHeapHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrRuntimeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrStringType.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeFactory.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ClrTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/Implementation/ComSyncBlock.cs, src/Microsoft.Diagnostics.Runtime/Implementation/FullSyncBlock.cs, src/Microsoft.Diagnostics.Runtime/Implementation/SyncBlockContainer.cs
Clean up the internal workings of ClrHeap.  This shouldn't have any external functionality changes.
=> Clean up ClrHeap internals

doc/ReleaseNotes3.0.md
=> Create release notes for 3.0

src/Microsoft.Diagnostics.Runtime.Utilities/DbgEng/DbgEngIDataReader.cs, src/Microsoft.Diagnostics.Runtime/DacInterface/DacDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Registers/RiscV64Context.cs, src/Microsoft.Diagnostics.Runtime/DbgEng/ImageFileMachine.cs, src/Microsoft.Diagnostics.Runtime/Implementation/DacImplementation.cs, src/Microsoft.Diagnostics.Runtime/Linux/ElfCoreFile.cs, src/Microsoft.Diagnostics.Runtime/Linux/IElfPRStatus.cs, src/Microsoft.Diagnostics.Runtime/Linux/LinuxLiveDataReader.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfHeaderCommon.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfMachine.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/ElfPRStatusRiscV64.cs, src/Microsoft.Diagnostics.Runtime/Linux/Structs/RegSetRiscV64.cs, src/Samples/DbgEngExtension/MAddress.cs
Based on CoreCLR changes.
CC @clamp03 @wscho77 @HJLeee @JongHeonChoi @t-mustafin @gbalykov
=> Initial Patch for RISC-V support.

src/Microsoft.Diagnostics.Runtime/DataReaders/Core/CoreDumpReader.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Registers/RiscV64Context.cs, src/Microsoft.Diagnostics.Runtime/Linux/ElfCoreFile.cs
Minor fixes and improvements for RISC-V related code.
CC @clamp03 @wscho77 @HJLeee @JongHeonChoi @t-mustafin @gbalykov
=> [RISC-V] Minor fixes.

src/Microsoft.Diagnostics.Runtime/Implementation/DacTypeProvider.cs
Fix regression introduced by #1206.
=> Fix a few issues in locating methods

azure-pipelines.yml
See https://github.com/dotnet/arcade/issues/13963
This should be merged together with https://github.com/microsoft/clrmd/pull/1213
/cc @leculver
=> Remove DotNet-Blob-Feed variable group from azure-pipelines.yml

src/Microsoft.Diagnostics.Runtime/AbstractDac/IAbstractModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/AbstractDac/IAbstractTypeHelpers.cs, src/Microsoft.Diagnostics.Runtime/ClrStaticField.cs, src/Microsoft.Diagnostics.Runtime/ClrThreadStaticField.cs, src/Microsoft.Diagnostics.Runtime/ClrType.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacModuleHelpers.cs, src/Microsoft.Diagnostics.Runtime/DacImplementation/DacTypeHelpers.cs
- Lack of ThreadStatics
- Static struct variables were not returned properly
=> Fix issues with statics

src/Microsoft.Diagnostics.Runtime/CustomDataTarget.cs
Fix an issue where we forgot to set the SymbolTokenCredential property.  Additionally make this an optional paramter.
=> Fix issue with TokenCredential

src/Microsoft.Diagnostics.Runtime/CustomDataTarget.cs, src/Microsoft.Diagnostics.Runtime/DataTarget.cs, src/Microsoft.Diagnostics.Runtime/Microsoft.Diagnostics.Runtime.csproj, src/Microsoft.Diagnostics.Runtime/SpecialDiagInfo.cs
Need the lowest common denominator version for System.Collections.Immutable
Add ForceCompleteRuntimeEnumeration CustomTarget property
=> Add SpecialDiagInfo block short cut for runtime module enumeration

src/Microsoft.Diagnostics.Runtime/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/DataTarget.cs
- Fix transposed filesize/timestamp
- Add TokenCredential parameter to CreateFromDbgEng
=> Fixes for CreateFromDbgEng

src/Microsoft.Diagnostics.Runtime/DataReaders/Core/CoreDumpReader.cs
Changed the boolean parameter in the PEModuleInfo constructor from false to true within CoreDumpReader.cs (https://github.com/microsoft/clrmd/issues/1279)
=> Changed the boolean parameter in the PEModuleInfo constructor from false to true

src/Microsoft.Diagnostics.Runtime/DataReaders/DbgEng/DbgEngDataReader.cs, src/Microsoft.Diagnostics.Runtime/DataReaders/Registers/LoongArch64Context.cs
Adjust the offset and Size field size in the LoongArch64Context structure.
@shushanhf
=> [LoongArch64] Fix the LoongArch64Context structure for LoongArch64

azure-pipelines-internal.yml
Enable internal compliance tools on internal builds.
=> Enable TSA and PoliCheck on Internal Builds

src/Microsoft.Diagnostics.Runtime/Implementation/SymbolServer.cs
Use UriBuilder and related methods to ensure we don't pull a query into the Uri we end up passing to symbol server requests.
=> Use UriBuilder to sanitize URLs
